// Code generated by protoc-gen-gogo.
// source: persist.proto
// DO NOT EDIT!

package types

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import api "github.com/hyperhq/runv/api"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type PersistPodLayout struct {
	Id         string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	GlobalSpec string   `protobuf:"bytes,11,opt,name=globalSpec,proto3" json:"globalSpec,omitempty"`
	Containers []string `protobuf:"bytes,21,rep,name=containers" json:"containers,omitempty"`
	Volumes    []string `protobuf:"bytes,22,rep,name=volumes" json:"volumes,omitempty"`
	Interfaces []string `protobuf:"bytes,23,rep,name=interfaces" json:"interfaces,omitempty"`
}

func (m *PersistPodLayout) Reset()         { *m = PersistPodLayout{} }
func (m *PersistPodLayout) String() string { return proto.CompactTextString(m) }
func (*PersistPodLayout) ProtoMessage()    {}

type PersistPodMeta struct {
	Id        string            `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Services  []*UserService    `protobuf:"bytes,11,rep,name=services" json:"services,omitempty"`
	Labels    map[string]string `protobuf:"bytes,12,rep,name=labels" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	CreatedAt int64             `protobuf:"varint,21,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
}

func (m *PersistPodMeta) Reset()         { *m = PersistPodMeta{} }
func (m *PersistPodMeta) String() string { return proto.CompactTextString(m) }
func (*PersistPodMeta) ProtoMessage()    {}

func (m *PersistPodMeta) GetServices() []*UserService {
	if m != nil {
		return m.Services
	}
	return nil
}

func (m *PersistPodMeta) GetLabels() map[string]string {
	if m != nil {
		return m.Labels
	}
	return nil
}

type SandboxPersistInfo struct {
	Id          string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PersistInfo []byte `protobuf:"bytes,2,opt,name=PersistInfo,proto3" json:"PersistInfo,omitempty"`
}

func (m *SandboxPersistInfo) Reset()         { *m = SandboxPersistInfo{} }
func (m *SandboxPersistInfo) String() string { return proto.CompactTextString(m) }
func (*SandboxPersistInfo) ProtoMessage()    {}

type PersistContainer struct {
	Id       string                    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Pod      string                    `protobuf:"bytes,2,opt,name=pod,proto3" json:"pod,omitempty"`
	Spec     *UserContainer            `protobuf:"bytes,11,opt,name=spec" json:"spec,omitempty"`
	Descript *api.ContainerDescription `protobuf:"bytes,12,opt,name=descript" json:"descript,omitempty"`
}

func (m *PersistContainer) Reset()         { *m = PersistContainer{} }
func (m *PersistContainer) String() string { return proto.CompactTextString(m) }
func (*PersistContainer) ProtoMessage()    {}

func (m *PersistContainer) GetSpec() *UserContainer {
	if m != nil {
		return m.Spec
	}
	return nil
}

func (m *PersistContainer) GetDescript() *api.ContainerDescription {
	if m != nil {
		return m.Descript
	}
	return nil
}

type PersistVolume struct {
	Name     string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Pod      string                 `protobuf:"bytes,2,opt,name=pod,proto3" json:"pod,omitempty"`
	Spec     *UserVolume            `protobuf:"bytes,11,opt,name=spec" json:"spec,omitempty"`
	Descript *api.VolumeDescription `protobuf:"bytes,12,opt,name=descript" json:"descript,omitempty"`
}

func (m *PersistVolume) Reset()         { *m = PersistVolume{} }
func (m *PersistVolume) String() string { return proto.CompactTextString(m) }
func (*PersistVolume) ProtoMessage()    {}

func (m *PersistVolume) GetSpec() *UserVolume {
	if m != nil {
		return m.Spec
	}
	return nil
}

func (m *PersistVolume) GetDescript() *api.VolumeDescription {
	if m != nil {
		return m.Descript
	}
	return nil
}

type PersistInterface struct {
	Id       string                    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Pod      string                    `protobuf:"bytes,2,opt,name=pod,proto3" json:"pod,omitempty"`
	Spec     *UserInterface            `protobuf:"bytes,11,opt,name=spec" json:"spec,omitempty"`
	Descript *api.InterfaceDescription `protobuf:"bytes,12,opt,name=descript" json:"descript,omitempty"`
}

func (m *PersistInterface) Reset()         { *m = PersistInterface{} }
func (m *PersistInterface) String() string { return proto.CompactTextString(m) }
func (*PersistInterface) ProtoMessage()    {}

func (m *PersistInterface) GetSpec() *UserInterface {
	if m != nil {
		return m.Spec
	}
	return nil
}

func (m *PersistInterface) GetDescript() *api.InterfaceDescription {
	if m != nil {
		return m.Descript
	}
	return nil
}

func init() {
	proto.RegisterType((*PersistPodLayout)(nil), "types.PersistPodLayout")
	proto.RegisterType((*PersistPodMeta)(nil), "types.PersistPodMeta")
	proto.RegisterType((*SandboxPersistInfo)(nil), "types.SandboxPersistInfo")
	proto.RegisterType((*PersistContainer)(nil), "types.PersistContainer")
	proto.RegisterType((*PersistVolume)(nil), "types.PersistVolume")
	proto.RegisterType((*PersistInterface)(nil), "types.PersistInterface")
}
