// Code generated by protoc-gen-go.
// source: types/types.proto
// DO NOT EDIT!

/*
Package types is a generated protocol buffer package.

It is generated from these files:
	types/types.proto

It has these top-level messages:
	ContainerPort
	EnvironmentVar
	VolumeMount
	WaitingStatus
	RunningStatus
	TermStatus
	ContainerStatus
	ContainerInfo
	Container
	RBDVolumeSource
	PodVolume
	PodSpec
	PodStatus
	PodInfo
	ImageInfo
	PodInfoRequest
	PodInfoResponse
	PodListRequest
	PodListResult
	PodListResponse
	ContainerListRequest
	ContainerListResult
	ContainerListResponse
	ContainerInfoRequest
	ContainerInfoResponse
	VMListResult
	VMListRequest
	VMListResponse
	ImageListRequest
	ImageListResponse
	VMCreateRequest
	VMCreateResponse
	VMRemoveRequest
	VMRemoveResponse
	UserContainerPort
	UserVolumeReference
	UserFileReference
	UserContainer
	UserResource
	UserFile
	UserVolumeOption
	UserVolume
	UserInterface
	UserServiceBackend
	UserService
	PodLogConfig
	PortmappingWhiteList
	UserPod
	PodCreateRequest
	PodCreateResponse
	PodRemoveRequest
	PodRemoveResponse
	ContainerLogsRequest
	ContainerLogsResponse
	DriverStatus
	InfoRequest
	InfoResponse
	ContainerExecRequest
	ContainerExecResponse
	PodStartMessage
	WaitRequest
	WaitResponse
*/
package types

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Types definitions for HyperContainer
type ContainerPort struct {
	Name          string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	HostPort      int32  `protobuf:"varint,2,opt,name=hostPort" json:"hostPort,omitempty"`
	ContainerPort int32  `protobuf:"varint,3,opt,name=containerPort" json:"containerPort,omitempty"`
	Protocol      string `protobuf:"bytes,4,opt,name=protocol" json:"protocol,omitempty"`
	HostIP        string `protobuf:"bytes,5,opt,name=hostIP" json:"hostIP,omitempty"`
}

func (m *ContainerPort) Reset()                    { *m = ContainerPort{} }
func (m *ContainerPort) String() string            { return proto.CompactTextString(m) }
func (*ContainerPort) ProtoMessage()               {}
func (*ContainerPort) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type EnvironmentVar struct {
	Env   string `protobuf:"bytes,1,opt,name=env" json:"env,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
}

func (m *EnvironmentVar) Reset()                    { *m = EnvironmentVar{} }
func (m *EnvironmentVar) String() string            { return proto.CompactTextString(m) }
func (*EnvironmentVar) ProtoMessage()               {}
func (*EnvironmentVar) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type VolumeMount struct {
	Name      string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	MountPath string `protobuf:"bytes,2,opt,name=mountPath" json:"mountPath,omitempty"`
	ReadOnly  bool   `protobuf:"varint,3,opt,name=readOnly" json:"readOnly,omitempty"`
}

func (m *VolumeMount) Reset()                    { *m = VolumeMount{} }
func (m *VolumeMount) String() string            { return proto.CompactTextString(m) }
func (*VolumeMount) ProtoMessage()               {}
func (*VolumeMount) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type WaitingStatus struct {
	Reason string `protobuf:"bytes,1,opt,name=reason" json:"reason,omitempty"`
}

func (m *WaitingStatus) Reset()                    { *m = WaitingStatus{} }
func (m *WaitingStatus) String() string            { return proto.CompactTextString(m) }
func (*WaitingStatus) ProtoMessage()               {}
func (*WaitingStatus) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type RunningStatus struct {
	StartedAt string `protobuf:"bytes,1,opt,name=startedAt" json:"startedAt,omitempty"`
}

func (m *RunningStatus) Reset()                    { *m = RunningStatus{} }
func (m *RunningStatus) String() string            { return proto.CompactTextString(m) }
func (*RunningStatus) ProtoMessage()               {}
func (*RunningStatus) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type TermStatus struct {
	ExitCode   int32  `protobuf:"varint,1,opt,name=exitCode" json:"exitCode,omitempty"`
	Reason     string `protobuf:"bytes,2,opt,name=reason" json:"reason,omitempty"`
	Message    string `protobuf:"bytes,3,opt,name=message" json:"message,omitempty"`
	StartedAt  string `protobuf:"bytes,4,opt,name=startedAt" json:"startedAt,omitempty"`
	FinishedAt string `protobuf:"bytes,5,opt,name=finishedAt" json:"finishedAt,omitempty"`
}

func (m *TermStatus) Reset()                    { *m = TermStatus{} }
func (m *TermStatus) String() string            { return proto.CompactTextString(m) }
func (*TermStatus) ProtoMessage()               {}
func (*TermStatus) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type ContainerStatus struct {
	Name        string         `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	ContainerID string         `protobuf:"bytes,2,opt,name=containerID" json:"containerID,omitempty"`
	Phase       string         `protobuf:"bytes,3,opt,name=phase" json:"phase,omitempty"`
	Waiting     *WaitingStatus `protobuf:"bytes,4,opt,name=waiting" json:"waiting,omitempty"`
	Running     *RunningStatus `protobuf:"bytes,5,opt,name=running" json:"running,omitempty"`
	Terminated  *TermStatus    `protobuf:"bytes,6,opt,name=terminated" json:"terminated,omitempty"`
}

func (m *ContainerStatus) Reset()                    { *m = ContainerStatus{} }
func (m *ContainerStatus) String() string            { return proto.CompactTextString(m) }
func (*ContainerStatus) ProtoMessage()               {}
func (*ContainerStatus) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *ContainerStatus) GetWaiting() *WaitingStatus {
	if m != nil {
		return m.Waiting
	}
	return nil
}

func (m *ContainerStatus) GetRunning() *RunningStatus {
	if m != nil {
		return m.Running
	}
	return nil
}

func (m *ContainerStatus) GetTerminated() *TermStatus {
	if m != nil {
		return m.Terminated
	}
	return nil
}

// TODO: embed Container message to avoid repetition
type ContainerInfo struct {
	Name            string            `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	ContainerID     string            `protobuf:"bytes,2,opt,name=containerID" json:"containerID,omitempty"`
	Image           string            `protobuf:"bytes,3,opt,name=image" json:"image,omitempty"`
	ImageID         string            `protobuf:"bytes,4,opt,name=imageID" json:"imageID,omitempty"`
	Commands        []string          `protobuf:"bytes,5,rep,name=commands" json:"commands,omitempty"`
	Args            []string          `protobuf:"bytes,6,rep,name=args" json:"args,omitempty"`
	WorkingDir      string            `protobuf:"bytes,7,opt,name=workingDir" json:"workingDir,omitempty"`
	Ports           []*ContainerPort  `protobuf:"bytes,8,rep,name=ports" json:"ports,omitempty"`
	Env             []*EnvironmentVar `protobuf:"bytes,9,rep,name=env" json:"env,omitempty"`
	VolumeMounts    []*VolumeMount    `protobuf:"bytes,10,rep,name=volumeMounts" json:"volumeMounts,omitempty"`
	Tty             bool              `protobuf:"varint,11,opt,name=tty" json:"tty,omitempty"`
	ImagePullPolicy string            `protobuf:"bytes,12,opt,name=imagePullPolicy" json:"imagePullPolicy,omitempty"`
	PodID           string            `protobuf:"bytes,13,opt,name=podID" json:"podID,omitempty"`
	Status          *ContainerStatus  `protobuf:"bytes,14,opt,name=status" json:"status,omitempty"`
}

func (m *ContainerInfo) Reset()                    { *m = ContainerInfo{} }
func (m *ContainerInfo) String() string            { return proto.CompactTextString(m) }
func (*ContainerInfo) ProtoMessage()               {}
func (*ContainerInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *ContainerInfo) GetPorts() []*ContainerPort {
	if m != nil {
		return m.Ports
	}
	return nil
}

func (m *ContainerInfo) GetEnv() []*EnvironmentVar {
	if m != nil {
		return m.Env
	}
	return nil
}

func (m *ContainerInfo) GetVolumeMounts() []*VolumeMount {
	if m != nil {
		return m.VolumeMounts
	}
	return nil
}

func (m *ContainerInfo) GetStatus() *ContainerStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

type Container struct {
	Name            string            `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	ContainerID     string            `protobuf:"bytes,2,opt,name=containerID" json:"containerID,omitempty"`
	Image           string            `protobuf:"bytes,3,opt,name=image" json:"image,omitempty"`
	ImageID         string            `protobuf:"bytes,4,opt,name=imageID" json:"imageID,omitempty"`
	Commands        []string          `protobuf:"bytes,5,rep,name=commands" json:"commands,omitempty"`
	Args            []string          `protobuf:"bytes,6,rep,name=args" json:"args,omitempty"`
	WorkingDir      string            `protobuf:"bytes,7,opt,name=workingDir" json:"workingDir,omitempty"`
	Ports           []*ContainerPort  `protobuf:"bytes,8,rep,name=ports" json:"ports,omitempty"`
	Env             []*EnvironmentVar `protobuf:"bytes,9,rep,name=env" json:"env,omitempty"`
	VolumeMounts    []*VolumeMount    `protobuf:"bytes,10,rep,name=volumeMounts" json:"volumeMounts,omitempty"`
	Tty             bool              `protobuf:"varint,11,opt,name=tty" json:"tty,omitempty"`
	ImagePullPolicy string            `protobuf:"bytes,12,opt,name=imagePullPolicy" json:"imagePullPolicy,omitempty"`
}

func (m *Container) Reset()                    { *m = Container{} }
func (m *Container) String() string            { return proto.CompactTextString(m) }
func (*Container) ProtoMessage()               {}
func (*Container) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *Container) GetPorts() []*ContainerPort {
	if m != nil {
		return m.Ports
	}
	return nil
}

func (m *Container) GetEnv() []*EnvironmentVar {
	if m != nil {
		return m.Env
	}
	return nil
}

func (m *Container) GetVolumeMounts() []*VolumeMount {
	if m != nil {
		return m.VolumeMounts
	}
	return nil
}

type RBDVolumeSource struct {
	Monitors []string `protobuf:"bytes,1,rep,name=monitors" json:"monitors,omitempty"`
	Image    string   `protobuf:"bytes,2,opt,name=image" json:"image,omitempty"`
	FsType   string   `protobuf:"bytes,3,opt,name=fsType" json:"fsType,omitempty"`
	Pool     string   `protobuf:"bytes,4,opt,name=pool" json:"pool,omitempty"`
	User     string   `protobuf:"bytes,5,opt,name=user" json:"user,omitempty"`
	Keyring  string   `protobuf:"bytes,6,opt,name=keyring" json:"keyring,omitempty"`
	ReadOnly bool     `protobuf:"varint,7,opt,name=readOnly" json:"readOnly,omitempty"`
}

func (m *RBDVolumeSource) Reset()                    { *m = RBDVolumeSource{} }
func (m *RBDVolumeSource) String() string            { return proto.CompactTextString(m) }
func (*RBDVolumeSource) ProtoMessage()               {}
func (*RBDVolumeSource) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

type PodVolume struct {
	Name   string           `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Source string           `protobuf:"bytes,2,opt,name=source" json:"source,omitempty"`
	Driver string           `protobuf:"bytes,3,opt,name=driver" json:"driver,omitempty"`
	Rbd    *RBDVolumeSource `protobuf:"bytes,4,opt,name=rbd" json:"rbd,omitempty"`
}

func (m *PodVolume) Reset()                    { *m = PodVolume{} }
func (m *PodVolume) String() string            { return proto.CompactTextString(m) }
func (*PodVolume) ProtoMessage()               {}
func (*PodVolume) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *PodVolume) GetRbd() *RBDVolumeSource {
	if m != nil {
		return m.Rbd
	}
	return nil
}

type PodSpec struct {
	Volumes    []*PodVolume      `protobuf:"bytes,1,rep,name=volumes" json:"volumes,omitempty"`
	Containers []*Container      `protobuf:"bytes,2,rep,name=containers" json:"containers,omitempty"`
	Labels     map[string]string `protobuf:"bytes,3,rep,name=labels" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Vcpu       int32             `protobuf:"varint,4,opt,name=vcpu" json:"vcpu,omitempty"`
	Memory     int32             `protobuf:"varint,5,opt,name=memory" json:"memory,omitempty"`
}

func (m *PodSpec) Reset()                    { *m = PodSpec{} }
func (m *PodSpec) String() string            { return proto.CompactTextString(m) }
func (*PodSpec) ProtoMessage()               {}
func (*PodSpec) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *PodSpec) GetVolumes() []*PodVolume {
	if m != nil {
		return m.Volumes
	}
	return nil
}

func (m *PodSpec) GetContainers() []*Container {
	if m != nil {
		return m.Containers
	}
	return nil
}

func (m *PodSpec) GetLabels() map[string]string {
	if m != nil {
		return m.Labels
	}
	return nil
}

type PodStatus struct {
	Phase           string             `protobuf:"bytes,1,opt,name=phase" json:"phase,omitempty"`
	Message         string             `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
	Reason          string             `protobuf:"bytes,3,opt,name=reason" json:"reason,omitempty"`
	HostIP          string             `protobuf:"bytes,4,opt,name=hostIP" json:"hostIP,omitempty"`
	PodIP           []string           `protobuf:"bytes,5,rep,name=podIP" json:"podIP,omitempty"`
	StartTime       string             `protobuf:"bytes,6,opt,name=startTime" json:"startTime,omitempty"`
	ContainerStatus []*ContainerStatus `protobuf:"bytes,7,rep,name=containerStatus" json:"containerStatus,omitempty"`
	FinishTime      string             `protobuf:"bytes,8,opt,name=finishTime" json:"finishTime,omitempty"`
}

func (m *PodStatus) Reset()                    { *m = PodStatus{} }
func (m *PodStatus) String() string            { return proto.CompactTextString(m) }
func (*PodStatus) ProtoMessage()               {}
func (*PodStatus) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *PodStatus) GetContainerStatus() []*ContainerStatus {
	if m != nil {
		return m.ContainerStatus
	}
	return nil
}

type PodInfo struct {
	Kind       string     `protobuf:"bytes,1,opt,name=kind" json:"kind,omitempty"`
	ApiVersion string     `protobuf:"bytes,2,opt,name=apiVersion" json:"apiVersion,omitempty"`
	Vm         string     `protobuf:"bytes,3,opt,name=vm" json:"vm,omitempty"`
	Spec       *PodSpec   `protobuf:"bytes,4,opt,name=spec" json:"spec,omitempty"`
	Status     *PodStatus `protobuf:"bytes,5,opt,name=status" json:"status,omitempty"`
}

func (m *PodInfo) Reset()                    { *m = PodInfo{} }
func (m *PodInfo) String() string            { return proto.CompactTextString(m) }
func (*PodInfo) ProtoMessage()               {}
func (*PodInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *PodInfo) GetSpec() *PodSpec {
	if m != nil {
		return m.Spec
	}
	return nil
}

func (m *PodInfo) GetStatus() *PodStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

type ImageInfo struct {
	Id          string            `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	ParentID    string            `protobuf:"bytes,2,opt,name=parentID" json:"parentID,omitempty"`
	RepoTags    []string          `protobuf:"bytes,3,rep,name=repoTags" json:"repoTags,omitempty"`
	RepoDigests []string          `protobuf:"bytes,4,rep,name=repoDigests" json:"repoDigests,omitempty"`
	Created     int64             `protobuf:"varint,5,opt,name=created" json:"created,omitempty"`
	VirtualSize int64             `protobuf:"varint,6,opt,name=virtualSize" json:"virtualSize,omitempty"`
	Labels      map[string]string `protobuf:"bytes,7,rep,name=labels" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *ImageInfo) Reset()                    { *m = ImageInfo{} }
func (m *ImageInfo) String() string            { return proto.CompactTextString(m) }
func (*ImageInfo) ProtoMessage()               {}
func (*ImageInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *ImageInfo) GetLabels() map[string]string {
	if m != nil {
		return m.Labels
	}
	return nil
}

type PodInfoRequest struct {
	PodID string `protobuf:"bytes,1,opt,name=podID" json:"podID,omitempty"`
}

func (m *PodInfoRequest) Reset()                    { *m = PodInfoRequest{} }
func (m *PodInfoRequest) String() string            { return proto.CompactTextString(m) }
func (*PodInfoRequest) ProtoMessage()               {}
func (*PodInfoRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

type PodInfoResponse struct {
	PodInfo *PodInfo `protobuf:"bytes,1,opt,name=podInfo" json:"podInfo,omitempty"`
}

func (m *PodInfoResponse) Reset()                    { *m = PodInfoResponse{} }
func (m *PodInfoResponse) String() string            { return proto.CompactTextString(m) }
func (*PodInfoResponse) ProtoMessage()               {}
func (*PodInfoResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *PodInfoResponse) GetPodInfo() *PodInfo {
	if m != nil {
		return m.PodInfo
	}
	return nil
}

type PodListRequest struct {
	PodID string `protobuf:"bytes,1,opt,name=podID" json:"podID,omitempty"`
	VmID  string `protobuf:"bytes,2,opt,name=vmID" json:"vmID,omitempty"`
}

func (m *PodListRequest) Reset()                    { *m = PodListRequest{} }
func (m *PodListRequest) String() string            { return proto.CompactTextString(m) }
func (*PodListRequest) ProtoMessage()               {}
func (*PodListRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

type PodListResult struct {
	PodID   string `protobuf:"bytes,1,opt,name=podID" json:"podID,omitempty"`
	PodName string `protobuf:"bytes,2,opt,name=podName" json:"podName,omitempty"`
	VmID    string `protobuf:"bytes,3,opt,name=vmID" json:"vmID,omitempty"`
	Status  string `protobuf:"bytes,4,opt,name=status" json:"status,omitempty"`
}

func (m *PodListResult) Reset()                    { *m = PodListResult{} }
func (m *PodListResult) String() string            { return proto.CompactTextString(m) }
func (*PodListResult) ProtoMessage()               {}
func (*PodListResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

type PodListResponse struct {
	PodList []*PodListResult `protobuf:"bytes,1,rep,name=podList" json:"podList,omitempty"`
}

func (m *PodListResponse) Reset()                    { *m = PodListResponse{} }
func (m *PodListResponse) String() string            { return proto.CompactTextString(m) }
func (*PodListResponse) ProtoMessage()               {}
func (*PodListResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{19} }

func (m *PodListResponse) GetPodList() []*PodListResult {
	if m != nil {
		return m.PodList
	}
	return nil
}

type ContainerListRequest struct {
	PodID     string `protobuf:"bytes,1,opt,name=podID" json:"podID,omitempty"`
	VmID      string `protobuf:"bytes,2,opt,name=vmID" json:"vmID,omitempty"`
	Auxiliary bool   `protobuf:"varint,3,opt,name=auxiliary" json:"auxiliary,omitempty"`
}

func (m *ContainerListRequest) Reset()                    { *m = ContainerListRequest{} }
func (m *ContainerListRequest) String() string            { return proto.CompactTextString(m) }
func (*ContainerListRequest) ProtoMessage()               {}
func (*ContainerListRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{20} }

type ContainerListResult struct {
	ContainerID   string `protobuf:"bytes,1,opt,name=containerID" json:"containerID,omitempty"`
	ContainerName string `protobuf:"bytes,2,opt,name=containerName" json:"containerName,omitempty"`
	PodID         string `protobuf:"bytes,3,opt,name=podID" json:"podID,omitempty"`
	Status        string `protobuf:"bytes,4,opt,name=status" json:"status,omitempty"`
}

func (m *ContainerListResult) Reset()                    { *m = ContainerListResult{} }
func (m *ContainerListResult) String() string            { return proto.CompactTextString(m) }
func (*ContainerListResult) ProtoMessage()               {}
func (*ContainerListResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{21} }

type ContainerListResponse struct {
	ContainerList []*ContainerListResult `protobuf:"bytes,1,rep,name=containerList" json:"containerList,omitempty"`
}

func (m *ContainerListResponse) Reset()                    { *m = ContainerListResponse{} }
func (m *ContainerListResponse) String() string            { return proto.CompactTextString(m) }
func (*ContainerListResponse) ProtoMessage()               {}
func (*ContainerListResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{22} }

func (m *ContainerListResponse) GetContainerList() []*ContainerListResult {
	if m != nil {
		return m.ContainerList
	}
	return nil
}

type ContainerInfoRequest struct {
	// container is the name or id of specified container
	Container string `protobuf:"bytes,1,opt,name=container" json:"container,omitempty"`
}

func (m *ContainerInfoRequest) Reset()                    { *m = ContainerInfoRequest{} }
func (m *ContainerInfoRequest) String() string            { return proto.CompactTextString(m) }
func (*ContainerInfoRequest) ProtoMessage()               {}
func (*ContainerInfoRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{23} }

type ContainerInfoResponse struct {
	ContainerInfo *ContainerInfo `protobuf:"bytes,1,opt,name=containerInfo" json:"containerInfo,omitempty"`
}

func (m *ContainerInfoResponse) Reset()                    { *m = ContainerInfoResponse{} }
func (m *ContainerInfoResponse) String() string            { return proto.CompactTextString(m) }
func (*ContainerInfoResponse) ProtoMessage()               {}
func (*ContainerInfoResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{24} }

func (m *ContainerInfoResponse) GetContainerInfo() *ContainerInfo {
	if m != nil {
		return m.ContainerInfo
	}
	return nil
}

type VMListResult struct {
	VmID   string `protobuf:"bytes,1,opt,name=vmID" json:"vmID,omitempty"`
	PodID  string `protobuf:"bytes,2,opt,name=podID" json:"podID,omitempty"`
	Status string `protobuf:"bytes,3,opt,name=status" json:"status,omitempty"`
}

func (m *VMListResult) Reset()                    { *m = VMListResult{} }
func (m *VMListResult) String() string            { return proto.CompactTextString(m) }
func (*VMListResult) ProtoMessage()               {}
func (*VMListResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{25} }

type VMListRequest struct {
	PodID string `protobuf:"bytes,1,opt,name=podID" json:"podID,omitempty"`
	VmID  string `protobuf:"bytes,2,opt,name=vmID" json:"vmID,omitempty"`
}

func (m *VMListRequest) Reset()                    { *m = VMListRequest{} }
func (m *VMListRequest) String() string            { return proto.CompactTextString(m) }
func (*VMListRequest) ProtoMessage()               {}
func (*VMListRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{26} }

type VMListResponse struct {
	VmList []*VMListResult `protobuf:"bytes,1,rep,name=vmList" json:"vmList,omitempty"`
}

func (m *VMListResponse) Reset()                    { *m = VMListResponse{} }
func (m *VMListResponse) String() string            { return proto.CompactTextString(m) }
func (*VMListResponse) ProtoMessage()               {}
func (*VMListResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{27} }

func (m *VMListResponse) GetVmList() []*VMListResult {
	if m != nil {
		return m.VmList
	}
	return nil
}

type ImageListRequest struct {
	// filterArgs is a JSON-encoded set of filter arguments
	FilterArgs string `protobuf:"bytes,1,opt,name=filterArgs" json:"filterArgs,omitempty"`
	// filter is a shell glob string applied to repository names
	Filter string `protobuf:"bytes,2,opt,name=filter" json:"filter,omitempty"`
	// all controls whether all images in the graph are filtered, or just the heads
	All bool `protobuf:"varint,3,opt,name=all" json:"all,omitempty"`
}

func (m *ImageListRequest) Reset()                    { *m = ImageListRequest{} }
func (m *ImageListRequest) String() string            { return proto.CompactTextString(m) }
func (*ImageListRequest) ProtoMessage()               {}
func (*ImageListRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{28} }

type ImageListResponse struct {
	ImageList []*ImageInfo `protobuf:"bytes,1,rep,name=imageList" json:"imageList,omitempty"`
}

func (m *ImageListResponse) Reset()                    { *m = ImageListResponse{} }
func (m *ImageListResponse) String() string            { return proto.CompactTextString(m) }
func (*ImageListResponse) ProtoMessage()               {}
func (*ImageListResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{29} }

func (m *ImageListResponse) GetImageList() []*ImageInfo {
	if m != nil {
		return m.ImageList
	}
	return nil
}

type VMCreateRequest struct {
	Cpu    int32 `protobuf:"varint,1,opt,name=cpu" json:"cpu,omitempty"`
	Memory int32 `protobuf:"varint,2,opt,name=memory" json:"memory,omitempty"`
}

func (m *VMCreateRequest) Reset()                    { *m = VMCreateRequest{} }
func (m *VMCreateRequest) String() string            { return proto.CompactTextString(m) }
func (*VMCreateRequest) ProtoMessage()               {}
func (*VMCreateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{30} }

type VMCreateResponse struct {
	VmID string `protobuf:"bytes,1,opt,name=vmID" json:"vmID,omitempty"`
}

func (m *VMCreateResponse) Reset()                    { *m = VMCreateResponse{} }
func (m *VMCreateResponse) String() string            { return proto.CompactTextString(m) }
func (*VMCreateResponse) ProtoMessage()               {}
func (*VMCreateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{31} }

type VMRemoveRequest struct {
	VmID string `protobuf:"bytes,1,opt,name=vmID" json:"vmID,omitempty"`
}

func (m *VMRemoveRequest) Reset()                    { *m = VMRemoveRequest{} }
func (m *VMRemoveRequest) String() string            { return proto.CompactTextString(m) }
func (*VMRemoveRequest) ProtoMessage()               {}
func (*VMRemoveRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{32} }

type VMRemoveResponse struct {
	Code  int32  `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
	Cause string `protobuf:"bytes,2,opt,name=cause" json:"cause,omitempty"`
}

func (m *VMRemoveResponse) Reset()                    { *m = VMRemoveResponse{} }
func (m *VMRemoveResponse) String() string            { return proto.CompactTextString(m) }
func (*VMRemoveResponse) ProtoMessage()               {}
func (*VMRemoveResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{33} }

type UserContainerPort struct {
	HostPort      int32  `protobuf:"varint,1,opt,name=hostPort" json:"hostPort,omitempty"`
	ContainerPort int32  `protobuf:"varint,2,opt,name=containerPort" json:"containerPort,omitempty"`
	ServicePort   int32  `protobuf:"varint,3,opt,name=servicePort" json:"servicePort,omitempty"`
	Protocol      string `protobuf:"bytes,4,opt,name=protocol" json:"protocol,omitempty"`
}

func (m *UserContainerPort) Reset()                    { *m = UserContainerPort{} }
func (m *UserContainerPort) String() string            { return proto.CompactTextString(m) }
func (*UserContainerPort) ProtoMessage()               {}
func (*UserContainerPort) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{34} }

type UserVolumeReference struct {
	Path     string `protobuf:"bytes,1,opt,name=path" json:"path,omitempty"`
	Volume   string `protobuf:"bytes,2,opt,name=volume" json:"volume,omitempty"`
	ReadOnly bool   `protobuf:"varint,3,opt,name=readOnly" json:"readOnly,omitempty"`
}

func (m *UserVolumeReference) Reset()                    { *m = UserVolumeReference{} }
func (m *UserVolumeReference) String() string            { return proto.CompactTextString(m) }
func (*UserVolumeReference) ProtoMessage()               {}
func (*UserVolumeReference) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{35} }

type UserFileReference struct {
	Path     string `protobuf:"bytes,1,opt,name=path" json:"path,omitempty"`
	Filename string `protobuf:"bytes,2,opt,name=filename" json:"filename,omitempty"`
	Perm     string `protobuf:"bytes,3,opt,name=perm" json:"perm,omitempty"`
	User     string `protobuf:"bytes,4,opt,name=user" json:"user,omitempty"`
	Group    string `protobuf:"bytes,5,opt,name=group" json:"group,omitempty"`
}

func (m *UserFileReference) Reset()                    { *m = UserFileReference{} }
func (m *UserFileReference) String() string            { return proto.CompactTextString(m) }
func (*UserFileReference) ProtoMessage()               {}
func (*UserFileReference) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{36} }

type UserContainer struct {
	Name          string                 `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Image         string                 `protobuf:"bytes,2,opt,name=image" json:"image,omitempty"`
	Workdir       string                 `protobuf:"bytes,3,opt,name=workdir" json:"workdir,omitempty"`
	RestartPolicy string                 `protobuf:"bytes,4,opt,name=restartPolicy" json:"restartPolicy,omitempty"`
	Tty           bool                   `protobuf:"varint,5,opt,name=tty" json:"tty,omitempty"`
	Sysctl        map[string]string      `protobuf:"bytes,6,rep,name=sysctl" json:"sysctl,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Envs          []*EnvironmentVar      `protobuf:"bytes,7,rep,name=envs" json:"envs,omitempty"`
	Command       []string               `protobuf:"bytes,8,rep,name=command" json:"command,omitempty"`
	Entrypoint    []string               `protobuf:"bytes,9,rep,name=entrypoint" json:"entrypoint,omitempty"`
	Ports         []*UserContainerPort   `protobuf:"bytes,10,rep,name=ports" json:"ports,omitempty"`
	Volumes       []*UserVolumeReference `protobuf:"bytes,11,rep,name=volumes" json:"volumes,omitempty"`
	Files         []*UserFileReference   `protobuf:"bytes,12,rep,name=files" json:"files,omitempty"`
}

func (m *UserContainer) Reset()                    { *m = UserContainer{} }
func (m *UserContainer) String() string            { return proto.CompactTextString(m) }
func (*UserContainer) ProtoMessage()               {}
func (*UserContainer) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{37} }

func (m *UserContainer) GetSysctl() map[string]string {
	if m != nil {
		return m.Sysctl
	}
	return nil
}

func (m *UserContainer) GetEnvs() []*EnvironmentVar {
	if m != nil {
		return m.Envs
	}
	return nil
}

func (m *UserContainer) GetPorts() []*UserContainerPort {
	if m != nil {
		return m.Ports
	}
	return nil
}

func (m *UserContainer) GetVolumes() []*UserVolumeReference {
	if m != nil {
		return m.Volumes
	}
	return nil
}

func (m *UserContainer) GetFiles() []*UserFileReference {
	if m != nil {
		return m.Files
	}
	return nil
}

type UserResource struct {
	Vcpu   int32 `protobuf:"varint,1,opt,name=vcpu" json:"vcpu,omitempty"`
	Memory int32 `protobuf:"varint,2,opt,name=memory" json:"memory,omitempty"`
}

func (m *UserResource) Reset()                    { *m = UserResource{} }
func (m *UserResource) String() string            { return proto.CompactTextString(m) }
func (*UserResource) ProtoMessage()               {}
func (*UserResource) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{38} }

type UserFile struct {
	Name     string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Encoding string `protobuf:"bytes,2,opt,name=encoding" json:"encoding,omitempty"`
	Uri      string `protobuf:"bytes,3,opt,name=uri" json:"uri,omitempty"`
	Content  string `protobuf:"bytes,4,opt,name=content" json:"content,omitempty"`
}

func (m *UserFile) Reset()                    { *m = UserFile{} }
func (m *UserFile) String() string            { return proto.CompactTextString(m) }
func (*UserFile) ProtoMessage()               {}
func (*UserFile) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{39} }

type UserVolumeOption struct {
	User     string   `protobuf:"bytes,1,opt,name=user" json:"user,omitempty"`
	Keyring  string   `protobuf:"bytes,2,opt,name=keyring" json:"keyring,omitempty"`
	Monitors []string `protobuf:"bytes,3,rep,name=monitors" json:"monitors,omitempty"`
}

func (m *UserVolumeOption) Reset()                    { *m = UserVolumeOption{} }
func (m *UserVolumeOption) String() string            { return proto.CompactTextString(m) }
func (*UserVolumeOption) ProtoMessage()               {}
func (*UserVolumeOption) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{40} }

type UserVolume struct {
	Name   string            `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Source string            `protobuf:"bytes,2,opt,name=source" json:"source,omitempty"`
	Driver string            `protobuf:"bytes,3,opt,name=driver" json:"driver,omitempty"`
	Option *UserVolumeOption `protobuf:"bytes,4,opt,name=option" json:"option,omitempty"`
}

func (m *UserVolume) Reset()                    { *m = UserVolume{} }
func (m *UserVolume) String() string            { return proto.CompactTextString(m) }
func (*UserVolume) ProtoMessage()               {}
func (*UserVolume) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{41} }

func (m *UserVolume) GetOption() *UserVolumeOption {
	if m != nil {
		return m.Option
	}
	return nil
}

type UserInterface struct {
	Bridge  string `protobuf:"bytes,1,opt,name=bridge" json:"bridge,omitempty"`
	Ip      string `protobuf:"bytes,2,opt,name=ip" json:"ip,omitempty"`
	Ifname  string `protobuf:"bytes,3,opt,name=ifname" json:"ifname,omitempty"`
	Mac     string `protobuf:"bytes,4,opt,name=mac" json:"mac,omitempty"`
	Gateway string `protobuf:"bytes,5,opt,name=gateway" json:"gateway,omitempty"`
}

func (m *UserInterface) Reset()                    { *m = UserInterface{} }
func (m *UserInterface) String() string            { return proto.CompactTextString(m) }
func (*UserInterface) ProtoMessage()               {}
func (*UserInterface) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{42} }

type UserServiceBackend struct {
	Hostip   string `protobuf:"bytes,1,opt,name=hostip" json:"hostip,omitempty"`
	Hostport int32  `protobuf:"varint,2,opt,name=hostport" json:"hostport,omitempty"`
}

func (m *UserServiceBackend) Reset()                    { *m = UserServiceBackend{} }
func (m *UserServiceBackend) String() string            { return proto.CompactTextString(m) }
func (*UserServiceBackend) ProtoMessage()               {}
func (*UserServiceBackend) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{43} }

type UserService struct {
	Serviceip   string                `protobuf:"bytes,1,opt,name=serviceip" json:"serviceip,omitempty"`
	Protocol    string                `protobuf:"bytes,2,opt,name=protocol" json:"protocol,omitempty"`
	Serviceport int32                 `protobuf:"varint,3,opt,name=serviceport" json:"serviceport,omitempty"`
	Hosts       []*UserServiceBackend `protobuf:"bytes,4,rep,name=hosts" json:"hosts,omitempty"`
}

func (m *UserService) Reset()                    { *m = UserService{} }
func (m *UserService) String() string            { return proto.CompactTextString(m) }
func (*UserService) ProtoMessage()               {}
func (*UserService) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{44} }

func (m *UserService) GetHosts() []*UserServiceBackend {
	if m != nil {
		return m.Hosts
	}
	return nil
}

type PodLogConfig struct {
	Type   string            `protobuf:"bytes,1,opt,name=type" json:"type,omitempty"`
	Config map[string]string `protobuf:"bytes,2,rep,name=config" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *PodLogConfig) Reset()                    { *m = PodLogConfig{} }
func (m *PodLogConfig) String() string            { return proto.CompactTextString(m) }
func (*PodLogConfig) ProtoMessage()               {}
func (*PodLogConfig) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{45} }

func (m *PodLogConfig) GetConfig() map[string]string {
	if m != nil {
		return m.Config
	}
	return nil
}

type PortmappingWhiteList struct {
	// allowed internal networks in CIDR format for portmapping
	// Those networks could visit all container ports if portmapping is enabled
	InternalNetworks []string `protobuf:"bytes,1,rep,name=internalNetworks" json:"internalNetworks,omitempty"`
	// allowed external networks in CIDR format for portmapping
	// Those networks could only visit exposed ports if portmapping is enabled
	ExternalNetworks []string `protobuf:"bytes,2,rep,name=externalNetworks" json:"externalNetworks,omitempty"`
}

func (m *PortmappingWhiteList) Reset()                    { *m = PortmappingWhiteList{} }
func (m *PortmappingWhiteList) String() string            { return proto.CompactTextString(m) }
func (*PortmappingWhiteList) ProtoMessage()               {}
func (*PortmappingWhiteList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{46} }

type UserPod struct {
	// TODO: rename this to name (renaming will also change restful API)
	Id                    string                `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Hostname              string                `protobuf:"bytes,2,opt,name=hostname" json:"hostname,omitempty"`
	Type                  string                `protobuf:"bytes,3,opt,name=type" json:"type,omitempty"`
	RestartPolicy         string                `protobuf:"bytes,4,opt,name=restartPolicy" json:"restartPolicy,omitempty"`
	Tty                   bool                  `protobuf:"varint,5,opt,name=tty" json:"tty,omitempty"`
	Labels                map[string]string     `protobuf:"bytes,6,rep,name=labels" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Resource              *UserResource         `protobuf:"bytes,7,opt,name=resource" json:"resource,omitempty"`
	Log                   *PodLogConfig         `protobuf:"bytes,8,opt,name=log" json:"log,omitempty"`
	Dns                   []string              `protobuf:"bytes,9,rep,name=dns" json:"dns,omitempty"`
	Containers            []*UserContainer      `protobuf:"bytes,10,rep,name=containers" json:"containers,omitempty"`
	Files                 []*UserFile           `protobuf:"bytes,11,rep,name=files" json:"files,omitempty"`
	Volumes               []*UserVolume         `protobuf:"bytes,12,rep,name=volumes" json:"volumes,omitempty"`
	Interfaces            []*UserInterface      `protobuf:"bytes,13,rep,name=interfaces" json:"interfaces,omitempty"`
	Services              []*UserService        `protobuf:"bytes,14,rep,name=services" json:"services,omitempty"`
	PortmappingWhiteLists *PortmappingWhiteList `protobuf:"bytes,15,opt,name=portmappingWhiteLists" json:"portmappingWhiteLists,omitempty"`
}

func (m *UserPod) Reset()                    { *m = UserPod{} }
func (m *UserPod) String() string            { return proto.CompactTextString(m) }
func (*UserPod) ProtoMessage()               {}
func (*UserPod) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{47} }

func (m *UserPod) GetLabels() map[string]string {
	if m != nil {
		return m.Labels
	}
	return nil
}

func (m *UserPod) GetResource() *UserResource {
	if m != nil {
		return m.Resource
	}
	return nil
}

func (m *UserPod) GetLog() *PodLogConfig {
	if m != nil {
		return m.Log
	}
	return nil
}

func (m *UserPod) GetContainers() []*UserContainer {
	if m != nil {
		return m.Containers
	}
	return nil
}

func (m *UserPod) GetFiles() []*UserFile {
	if m != nil {
		return m.Files
	}
	return nil
}

func (m *UserPod) GetVolumes() []*UserVolume {
	if m != nil {
		return m.Volumes
	}
	return nil
}

func (m *UserPod) GetInterfaces() []*UserInterface {
	if m != nil {
		return m.Interfaces
	}
	return nil
}

func (m *UserPod) GetServices() []*UserService {
	if m != nil {
		return m.Services
	}
	return nil
}

func (m *UserPod) GetPortmappingWhiteLists() *PortmappingWhiteList {
	if m != nil {
		return m.PortmappingWhiteLists
	}
	return nil
}

type PodCreateRequest struct {
	PodSpec *UserPod `protobuf:"bytes,1,opt,name=podSpec" json:"podSpec,omitempty"`
	PodID   string   `protobuf:"bytes,2,opt,name=podID" json:"podID,omitempty"`
}

func (m *PodCreateRequest) Reset()                    { *m = PodCreateRequest{} }
func (m *PodCreateRequest) String() string            { return proto.CompactTextString(m) }
func (*PodCreateRequest) ProtoMessage()               {}
func (*PodCreateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{48} }

func (m *PodCreateRequest) GetPodSpec() *UserPod {
	if m != nil {
		return m.PodSpec
	}
	return nil
}

type PodCreateResponse struct {
	PodID string `protobuf:"bytes,1,opt,name=podID" json:"podID,omitempty"`
}

func (m *PodCreateResponse) Reset()                    { *m = PodCreateResponse{} }
func (m *PodCreateResponse) String() string            { return proto.CompactTextString(m) }
func (*PodCreateResponse) ProtoMessage()               {}
func (*PodCreateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{49} }

type PodRemoveRequest struct {
	PodID string `protobuf:"bytes,1,opt,name=podID" json:"podID,omitempty"`
}

func (m *PodRemoveRequest) Reset()                    { *m = PodRemoveRequest{} }
func (m *PodRemoveRequest) String() string            { return proto.CompactTextString(m) }
func (*PodRemoveRequest) ProtoMessage()               {}
func (*PodRemoveRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{50} }

type PodRemoveResponse struct {
	Code  int32  `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
	Cause string `protobuf:"bytes,2,opt,name=cause" json:"cause,omitempty"`
}

func (m *PodRemoveResponse) Reset()                    { *m = PodRemoveResponse{} }
func (m *PodRemoveResponse) String() string            { return proto.CompactTextString(m) }
func (*PodRemoveResponse) ProtoMessage()               {}
func (*PodRemoveResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{51} }

type ContainerLogsRequest struct {
	Container  string `protobuf:"bytes,1,opt,name=container" json:"container,omitempty"`
	Follow     bool   `protobuf:"varint,2,opt,name=follow" json:"follow,omitempty"`
	Timestamps bool   `protobuf:"varint,3,opt,name=timestamps" json:"timestamps,omitempty"`
	Tail       string `protobuf:"bytes,4,opt,name=tail" json:"tail,omitempty"`
	Since      string `protobuf:"bytes,5,opt,name=since" json:"since,omitempty"`
	Stdout     bool   `protobuf:"varint,6,opt,name=stdout" json:"stdout,omitempty"`
	Stderr     bool   `protobuf:"varint,7,opt,name=stderr" json:"stderr,omitempty"`
}

func (m *ContainerLogsRequest) Reset()                    { *m = ContainerLogsRequest{} }
func (m *ContainerLogsRequest) String() string            { return proto.CompactTextString(m) }
func (*ContainerLogsRequest) ProtoMessage()               {}
func (*ContainerLogsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{52} }

type ContainerLogsResponse struct {
	Log []byte `protobuf:"bytes,1,opt,name=log,proto3" json:"log,omitempty"`
}

func (m *ContainerLogsResponse) Reset()                    { *m = ContainerLogsResponse{} }
func (m *ContainerLogsResponse) String() string            { return proto.CompactTextString(m) }
func (*ContainerLogsResponse) ProtoMessage()               {}
func (*ContainerLogsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{53} }

type DriverStatus struct {
	Name   string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Status string `protobuf:"bytes,2,opt,name=status" json:"status,omitempty"`
}

func (m *DriverStatus) Reset()                    { *m = DriverStatus{} }
func (m *DriverStatus) String() string            { return proto.CompactTextString(m) }
func (*DriverStatus) ProtoMessage()               {}
func (*DriverStatus) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{54} }

type InfoRequest struct {
}

func (m *InfoRequest) Reset()                    { *m = InfoRequest{} }
func (m *InfoRequest) String() string            { return proto.CompactTextString(m) }
func (*InfoRequest) ProtoMessage()               {}
func (*InfoRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{55} }

type InfoResponse struct {
	ID                 string          `protobuf:"bytes,1,opt,name=ID,json=iD" json:"ID,omitempty"`
	Containers         int32           `protobuf:"varint,2,opt,name=containers" json:"containers,omitempty"`
	Images             int32           `protobuf:"varint,3,opt,name=images" json:"images,omitempty"`
	Driver             string          `protobuf:"bytes,4,opt,name=driver" json:"driver,omitempty"`
	Dstatus            []*DriverStatus `protobuf:"bytes,5,rep,name=dstatus" json:"dstatus,omitempty"`
	DockerRootDir      string          `protobuf:"bytes,6,opt,name=dockerRootDir" json:"dockerRootDir,omitempty"`
	IndexServerAddress string          `protobuf:"bytes,7,opt,name=indexServerAddress" json:"indexServerAddress,omitempty"`
	ExecutionDriver    string          `protobuf:"bytes,8,opt,name=executionDriver" json:"executionDriver,omitempty"`
	MemTotal           int64           `protobuf:"varint,9,opt,name=memTotal" json:"memTotal,omitempty"`
	Pods               int64           `protobuf:"varint,10,opt,name=pods" json:"pods,omitempty"`
	OperatingSystem    string          `protobuf:"bytes,11,opt,name=operatingSystem" json:"operatingSystem,omitempty"`
	Name               string          `protobuf:"bytes,12,opt,name=name" json:"name,omitempty"`
}

func (m *InfoResponse) Reset()                    { *m = InfoResponse{} }
func (m *InfoResponse) String() string            { return proto.CompactTextString(m) }
func (*InfoResponse) ProtoMessage()               {}
func (*InfoResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{56} }

func (m *InfoResponse) GetDstatus() []*DriverStatus {
	if m != nil {
		return m.Dstatus
	}
	return nil
}

type ContainerExecRequest struct {
	ContainerID string   `protobuf:"bytes,1,opt,name=containerID" json:"containerID,omitempty"`
	Command     []string `protobuf:"bytes,2,rep,name=command" json:"command,omitempty"`
	Tag         string   `protobuf:"bytes,3,opt,name=tag" json:"tag,omitempty"`
	Tty         bool     `protobuf:"varint,4,opt,name=tty" json:"tty,omitempty"`
	Stdin       []byte   `protobuf:"bytes,5,opt,name=stdin,proto3" json:"stdin,omitempty"`
}

func (m *ContainerExecRequest) Reset()                    { *m = ContainerExecRequest{} }
func (m *ContainerExecRequest) String() string            { return proto.CompactTextString(m) }
func (*ContainerExecRequest) ProtoMessage()               {}
func (*ContainerExecRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{57} }

type ContainerExecResponse struct {
	Stdout []byte `protobuf:"bytes,1,opt,name=stdout,proto3" json:"stdout,omitempty"`
}

func (m *ContainerExecResponse) Reset()                    { *m = ContainerExecResponse{} }
func (m *ContainerExecResponse) String() string            { return proto.CompactTextString(m) }
func (*ContainerExecResponse) ProtoMessage()               {}
func (*ContainerExecResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{58} }

type PodStartMessage struct {
	PodID string `protobuf:"bytes,1,opt,name=podID" json:"podID,omitempty"`
	VmID  string `protobuf:"bytes,2,opt,name=vmID" json:"vmID,omitempty"`
	Tag   string `protobuf:"bytes,3,opt,name=tag" json:"tag,omitempty"`
	Data  []byte `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
}

func (m *PodStartMessage) Reset()                    { *m = PodStartMessage{} }
func (m *PodStartMessage) String() string            { return proto.CompactTextString(m) }
func (*PodStartMessage) ProtoMessage()               {}
func (*PodStartMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{59} }

type WaitRequest struct {
	Container string `protobuf:"bytes,1,opt,name=container" json:"container,omitempty"`
	ProcessId string `protobuf:"bytes,2,opt,name=processId" json:"processId,omitempty"`
	NoHang    bool   `protobuf:"varint,3,opt,name=noHang" json:"noHang,omitempty"`
}

func (m *WaitRequest) Reset()                    { *m = WaitRequest{} }
func (m *WaitRequest) String() string            { return proto.CompactTextString(m) }
func (*WaitRequest) ProtoMessage()               {}
func (*WaitRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{60} }

type WaitResponse struct {
	ExitCode int32 `protobuf:"varint,1,opt,name=exitCode" json:"exitCode,omitempty"`
}

func (m *WaitResponse) Reset()                    { *m = WaitResponse{} }
func (m *WaitResponse) String() string            { return proto.CompactTextString(m) }
func (*WaitResponse) ProtoMessage()               {}
func (*WaitResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{61} }

func init() {
	proto.RegisterType((*ContainerPort)(nil), "types.ContainerPort")
	proto.RegisterType((*EnvironmentVar)(nil), "types.EnvironmentVar")
	proto.RegisterType((*VolumeMount)(nil), "types.VolumeMount")
	proto.RegisterType((*WaitingStatus)(nil), "types.WaitingStatus")
	proto.RegisterType((*RunningStatus)(nil), "types.RunningStatus")
	proto.RegisterType((*TermStatus)(nil), "types.TermStatus")
	proto.RegisterType((*ContainerStatus)(nil), "types.ContainerStatus")
	proto.RegisterType((*ContainerInfo)(nil), "types.ContainerInfo")
	proto.RegisterType((*Container)(nil), "types.Container")
	proto.RegisterType((*RBDVolumeSource)(nil), "types.RBDVolumeSource")
	proto.RegisterType((*PodVolume)(nil), "types.PodVolume")
	proto.RegisterType((*PodSpec)(nil), "types.PodSpec")
	proto.RegisterType((*PodStatus)(nil), "types.PodStatus")
	proto.RegisterType((*PodInfo)(nil), "types.PodInfo")
	proto.RegisterType((*ImageInfo)(nil), "types.ImageInfo")
	proto.RegisterType((*PodInfoRequest)(nil), "types.PodInfoRequest")
	proto.RegisterType((*PodInfoResponse)(nil), "types.PodInfoResponse")
	proto.RegisterType((*PodListRequest)(nil), "types.PodListRequest")
	proto.RegisterType((*PodListResult)(nil), "types.PodListResult")
	proto.RegisterType((*PodListResponse)(nil), "types.PodListResponse")
	proto.RegisterType((*ContainerListRequest)(nil), "types.ContainerListRequest")
	proto.RegisterType((*ContainerListResult)(nil), "types.ContainerListResult")
	proto.RegisterType((*ContainerListResponse)(nil), "types.ContainerListResponse")
	proto.RegisterType((*ContainerInfoRequest)(nil), "types.ContainerInfoRequest")
	proto.RegisterType((*ContainerInfoResponse)(nil), "types.ContainerInfoResponse")
	proto.RegisterType((*VMListResult)(nil), "types.VMListResult")
	proto.RegisterType((*VMListRequest)(nil), "types.VMListRequest")
	proto.RegisterType((*VMListResponse)(nil), "types.VMListResponse")
	proto.RegisterType((*ImageListRequest)(nil), "types.ImageListRequest")
	proto.RegisterType((*ImageListResponse)(nil), "types.ImageListResponse")
	proto.RegisterType((*VMCreateRequest)(nil), "types.VMCreateRequest")
	proto.RegisterType((*VMCreateResponse)(nil), "types.VMCreateResponse")
	proto.RegisterType((*VMRemoveRequest)(nil), "types.VMRemoveRequest")
	proto.RegisterType((*VMRemoveResponse)(nil), "types.VMRemoveResponse")
	proto.RegisterType((*UserContainerPort)(nil), "types.UserContainerPort")
	proto.RegisterType((*UserVolumeReference)(nil), "types.UserVolumeReference")
	proto.RegisterType((*UserFileReference)(nil), "types.UserFileReference")
	proto.RegisterType((*UserContainer)(nil), "types.UserContainer")
	proto.RegisterType((*UserResource)(nil), "types.UserResource")
	proto.RegisterType((*UserFile)(nil), "types.UserFile")
	proto.RegisterType((*UserVolumeOption)(nil), "types.UserVolumeOption")
	proto.RegisterType((*UserVolume)(nil), "types.UserVolume")
	proto.RegisterType((*UserInterface)(nil), "types.UserInterface")
	proto.RegisterType((*UserServiceBackend)(nil), "types.UserServiceBackend")
	proto.RegisterType((*UserService)(nil), "types.UserService")
	proto.RegisterType((*PodLogConfig)(nil), "types.PodLogConfig")
	proto.RegisterType((*PortmappingWhiteList)(nil), "types.PortmappingWhiteList")
	proto.RegisterType((*UserPod)(nil), "types.UserPod")
	proto.RegisterType((*PodCreateRequest)(nil), "types.PodCreateRequest")
	proto.RegisterType((*PodCreateResponse)(nil), "types.PodCreateResponse")
	proto.RegisterType((*PodRemoveRequest)(nil), "types.PodRemoveRequest")
	proto.RegisterType((*PodRemoveResponse)(nil), "types.PodRemoveResponse")
	proto.RegisterType((*ContainerLogsRequest)(nil), "types.ContainerLogsRequest")
	proto.RegisterType((*ContainerLogsResponse)(nil), "types.ContainerLogsResponse")
	proto.RegisterType((*DriverStatus)(nil), "types.DriverStatus")
	proto.RegisterType((*InfoRequest)(nil), "types.InfoRequest")
	proto.RegisterType((*InfoResponse)(nil), "types.InfoResponse")
	proto.RegisterType((*ContainerExecRequest)(nil), "types.ContainerExecRequest")
	proto.RegisterType((*ContainerExecResponse)(nil), "types.ContainerExecResponse")
	proto.RegisterType((*PodStartMessage)(nil), "types.PodStartMessage")
	proto.RegisterType((*WaitRequest)(nil), "types.WaitRequest")
	proto.RegisterType((*WaitResponse)(nil), "types.WaitResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion2

// Client API for PublicAPI service

type PublicAPIClient interface {
	// PodList implements GET /list?item=pod
	PodList(ctx context.Context, in *PodListRequest, opts ...grpc.CallOption) (*PodListResponse, error)
	// PodCreate implements POST /pod/create
	PodCreate(ctx context.Context, in *PodCreateRequest, opts ...grpc.CallOption) (*PodCreateResponse, error)
	// PodInfo implements GET /pod/info
	PodInfo(ctx context.Context, in *PodInfoRequest, opts ...grpc.CallOption) (*PodInfoResponse, error)
	// PodRemove implements  DELETE /pod
	PodRemove(ctx context.Context, in *PodRemoveRequest, opts ...grpc.CallOption) (*PodRemoveResponse, error)
	// ContainerList implements GET /list?item=container
	ContainerList(ctx context.Context, in *ContainerListRequest, opts ...grpc.CallOption) (*ContainerListResponse, error)
	// ContainerInfo implements GET /container/info
	ContainerInfo(ctx context.Context, in *ContainerInfoRequest, opts ...grpc.CallOption) (*ContainerInfoResponse, error)
	// ImageList implements GET /images/get
	ImageList(ctx context.Context, in *ImageListRequest, opts ...grpc.CallOption) (*ImageListResponse, error)
	// VMList implements GET /list?item=vm
	VMList(ctx context.Context, in *VMListRequest, opts ...grpc.CallOption) (*VMListResponse, error)
	// VMCreate implements POST /vm/create
	VMCreate(ctx context.Context, in *VMCreateRequest, opts ...grpc.CallOption) (*VMCreateResponse, error)
	// VMRemove implements DELETE /vm
	VMRemove(ctx context.Context, in *VMRemoveRequest, opts ...grpc.CallOption) (*VMRemoveResponse, error)
	// TODO: implements  GET    /pod/stats
	// TODO: implements  POST   /pod/labels
	// PodStart implements  POST   /pod/start
	PodStart(ctx context.Context, opts ...grpc.CallOption) (PublicAPI_PodStartClient, error)
	// ContainerLogs implements  GET  /container/logs
	ContainerLogs(ctx context.Context, in *ContainerLogsRequest, opts ...grpc.CallOption) (PublicAPI_ContainerLogsClient, error)
	// TODO: implements  POST   /container/create
	// TODO: implements  POST   /container/rename
	// TODO: implements  POST   /container/commit
	// TODO: implements  POST   /container/kill
	// ContainerExec implements  POST   /exec
	ContainerExec(ctx context.Context, opts ...grpc.CallOption) (PublicAPI_ContainerExecClient, error)
	// TODO: implements  POST   /attach
	// TODO: implements  POST   /tty/resize
	// Wait implements  GET    /exitcode
	Wait(ctx context.Context, in *WaitRequest, opts ...grpc.CallOption) (*WaitResponse, error)
	// TODO: implements  GET    /_ping
	// Info implements  GET    /info
	Info(ctx context.Context, in *InfoRequest, opts ...grpc.CallOption) (*InfoResponse, error)
}

type publicAPIClient struct {
	cc *grpc.ClientConn
}

func NewPublicAPIClient(cc *grpc.ClientConn) PublicAPIClient {
	return &publicAPIClient{cc}
}

func (c *publicAPIClient) PodList(ctx context.Context, in *PodListRequest, opts ...grpc.CallOption) (*PodListResponse, error) {
	out := new(PodListResponse)
	err := grpc.Invoke(ctx, "/types.PublicAPI/PodList", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *publicAPIClient) PodCreate(ctx context.Context, in *PodCreateRequest, opts ...grpc.CallOption) (*PodCreateResponse, error) {
	out := new(PodCreateResponse)
	err := grpc.Invoke(ctx, "/types.PublicAPI/PodCreate", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *publicAPIClient) PodInfo(ctx context.Context, in *PodInfoRequest, opts ...grpc.CallOption) (*PodInfoResponse, error) {
	out := new(PodInfoResponse)
	err := grpc.Invoke(ctx, "/types.PublicAPI/PodInfo", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *publicAPIClient) PodRemove(ctx context.Context, in *PodRemoveRequest, opts ...grpc.CallOption) (*PodRemoveResponse, error) {
	out := new(PodRemoveResponse)
	err := grpc.Invoke(ctx, "/types.PublicAPI/PodRemove", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *publicAPIClient) ContainerList(ctx context.Context, in *ContainerListRequest, opts ...grpc.CallOption) (*ContainerListResponse, error) {
	out := new(ContainerListResponse)
	err := grpc.Invoke(ctx, "/types.PublicAPI/ContainerList", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *publicAPIClient) ContainerInfo(ctx context.Context, in *ContainerInfoRequest, opts ...grpc.CallOption) (*ContainerInfoResponse, error) {
	out := new(ContainerInfoResponse)
	err := grpc.Invoke(ctx, "/types.PublicAPI/ContainerInfo", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *publicAPIClient) ImageList(ctx context.Context, in *ImageListRequest, opts ...grpc.CallOption) (*ImageListResponse, error) {
	out := new(ImageListResponse)
	err := grpc.Invoke(ctx, "/types.PublicAPI/ImageList", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *publicAPIClient) VMList(ctx context.Context, in *VMListRequest, opts ...grpc.CallOption) (*VMListResponse, error) {
	out := new(VMListResponse)
	err := grpc.Invoke(ctx, "/types.PublicAPI/VMList", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *publicAPIClient) VMCreate(ctx context.Context, in *VMCreateRequest, opts ...grpc.CallOption) (*VMCreateResponse, error) {
	out := new(VMCreateResponse)
	err := grpc.Invoke(ctx, "/types.PublicAPI/VMCreate", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *publicAPIClient) VMRemove(ctx context.Context, in *VMRemoveRequest, opts ...grpc.CallOption) (*VMRemoveResponse, error) {
	out := new(VMRemoveResponse)
	err := grpc.Invoke(ctx, "/types.PublicAPI/VMRemove", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *publicAPIClient) PodStart(ctx context.Context, opts ...grpc.CallOption) (PublicAPI_PodStartClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_PublicAPI_serviceDesc.Streams[0], c.cc, "/types.PublicAPI/PodStart", opts...)
	if err != nil {
		return nil, err
	}
	x := &publicAPIPodStartClient{stream}
	return x, nil
}

type PublicAPI_PodStartClient interface {
	Send(*PodStartMessage) error
	Recv() (*PodStartMessage, error)
	grpc.ClientStream
}

type publicAPIPodStartClient struct {
	grpc.ClientStream
}

func (x *publicAPIPodStartClient) Send(m *PodStartMessage) error {
	return x.ClientStream.SendMsg(m)
}

func (x *publicAPIPodStartClient) Recv() (*PodStartMessage, error) {
	m := new(PodStartMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *publicAPIClient) ContainerLogs(ctx context.Context, in *ContainerLogsRequest, opts ...grpc.CallOption) (PublicAPI_ContainerLogsClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_PublicAPI_serviceDesc.Streams[1], c.cc, "/types.PublicAPI/ContainerLogs", opts...)
	if err != nil {
		return nil, err
	}
	x := &publicAPIContainerLogsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type PublicAPI_ContainerLogsClient interface {
	Recv() (*ContainerLogsResponse, error)
	grpc.ClientStream
}

type publicAPIContainerLogsClient struct {
	grpc.ClientStream
}

func (x *publicAPIContainerLogsClient) Recv() (*ContainerLogsResponse, error) {
	m := new(ContainerLogsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *publicAPIClient) ContainerExec(ctx context.Context, opts ...grpc.CallOption) (PublicAPI_ContainerExecClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_PublicAPI_serviceDesc.Streams[2], c.cc, "/types.PublicAPI/ContainerExec", opts...)
	if err != nil {
		return nil, err
	}
	x := &publicAPIContainerExecClient{stream}
	return x, nil
}

type PublicAPI_ContainerExecClient interface {
	Send(*ContainerExecRequest) error
	Recv() (*ContainerExecResponse, error)
	grpc.ClientStream
}

type publicAPIContainerExecClient struct {
	grpc.ClientStream
}

func (x *publicAPIContainerExecClient) Send(m *ContainerExecRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *publicAPIContainerExecClient) Recv() (*ContainerExecResponse, error) {
	m := new(ContainerExecResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *publicAPIClient) Wait(ctx context.Context, in *WaitRequest, opts ...grpc.CallOption) (*WaitResponse, error) {
	out := new(WaitResponse)
	err := grpc.Invoke(ctx, "/types.PublicAPI/Wait", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *publicAPIClient) Info(ctx context.Context, in *InfoRequest, opts ...grpc.CallOption) (*InfoResponse, error) {
	out := new(InfoResponse)
	err := grpc.Invoke(ctx, "/types.PublicAPI/Info", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for PublicAPI service

type PublicAPIServer interface {
	// PodList implements GET /list?item=pod
	PodList(context.Context, *PodListRequest) (*PodListResponse, error)
	// PodCreate implements POST /pod/create
	PodCreate(context.Context, *PodCreateRequest) (*PodCreateResponse, error)
	// PodInfo implements GET /pod/info
	PodInfo(context.Context, *PodInfoRequest) (*PodInfoResponse, error)
	// PodRemove implements  DELETE /pod
	PodRemove(context.Context, *PodRemoveRequest) (*PodRemoveResponse, error)
	// ContainerList implements GET /list?item=container
	ContainerList(context.Context, *ContainerListRequest) (*ContainerListResponse, error)
	// ContainerInfo implements GET /container/info
	ContainerInfo(context.Context, *ContainerInfoRequest) (*ContainerInfoResponse, error)
	// ImageList implements GET /images/get
	ImageList(context.Context, *ImageListRequest) (*ImageListResponse, error)
	// VMList implements GET /list?item=vm
	VMList(context.Context, *VMListRequest) (*VMListResponse, error)
	// VMCreate implements POST /vm/create
	VMCreate(context.Context, *VMCreateRequest) (*VMCreateResponse, error)
	// VMRemove implements DELETE /vm
	VMRemove(context.Context, *VMRemoveRequest) (*VMRemoveResponse, error)
	// TODO: implements  GET    /pod/stats
	// TODO: implements  POST   /pod/labels
	// PodStart implements  POST   /pod/start
	PodStart(PublicAPI_PodStartServer) error
	// ContainerLogs implements  GET  /container/logs
	ContainerLogs(*ContainerLogsRequest, PublicAPI_ContainerLogsServer) error
	// TODO: implements  POST   /container/create
	// TODO: implements  POST   /container/rename
	// TODO: implements  POST   /container/commit
	// TODO: implements  POST   /container/kill
	// ContainerExec implements  POST   /exec
	ContainerExec(PublicAPI_ContainerExecServer) error
	// TODO: implements  POST   /attach
	// TODO: implements  POST   /tty/resize
	// Wait implements  GET    /exitcode
	Wait(context.Context, *WaitRequest) (*WaitResponse, error)
	// TODO: implements  GET    /_ping
	// Info implements  GET    /info
	Info(context.Context, *InfoRequest) (*InfoResponse, error)
}

func RegisterPublicAPIServer(s *grpc.Server, srv PublicAPIServer) {
	s.RegisterService(&_PublicAPI_serviceDesc, srv)
}

func _PublicAPI_PodList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PodListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PublicAPIServer).PodList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/types.PublicAPI/PodList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PublicAPIServer).PodList(ctx, req.(*PodListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PublicAPI_PodCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PodCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PublicAPIServer).PodCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/types.PublicAPI/PodCreate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PublicAPIServer).PodCreate(ctx, req.(*PodCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PublicAPI_PodInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PodInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PublicAPIServer).PodInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/types.PublicAPI/PodInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PublicAPIServer).PodInfo(ctx, req.(*PodInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PublicAPI_PodRemove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PodRemoveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PublicAPIServer).PodRemove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/types.PublicAPI/PodRemove",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PublicAPIServer).PodRemove(ctx, req.(*PodRemoveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PublicAPI_ContainerList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContainerListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PublicAPIServer).ContainerList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/types.PublicAPI/ContainerList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PublicAPIServer).ContainerList(ctx, req.(*ContainerListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PublicAPI_ContainerInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContainerInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PublicAPIServer).ContainerInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/types.PublicAPI/ContainerInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PublicAPIServer).ContainerInfo(ctx, req.(*ContainerInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PublicAPI_ImageList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImageListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PublicAPIServer).ImageList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/types.PublicAPI/ImageList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PublicAPIServer).ImageList(ctx, req.(*ImageListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PublicAPI_VMList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VMListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PublicAPIServer).VMList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/types.PublicAPI/VMList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PublicAPIServer).VMList(ctx, req.(*VMListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PublicAPI_VMCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VMCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PublicAPIServer).VMCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/types.PublicAPI/VMCreate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PublicAPIServer).VMCreate(ctx, req.(*VMCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PublicAPI_VMRemove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VMRemoveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PublicAPIServer).VMRemove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/types.PublicAPI/VMRemove",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PublicAPIServer).VMRemove(ctx, req.(*VMRemoveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PublicAPI_PodStart_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PublicAPIServer).PodStart(&publicAPIPodStartServer{stream})
}

type PublicAPI_PodStartServer interface {
	Send(*PodStartMessage) error
	Recv() (*PodStartMessage, error)
	grpc.ServerStream
}

type publicAPIPodStartServer struct {
	grpc.ServerStream
}

func (x *publicAPIPodStartServer) Send(m *PodStartMessage) error {
	return x.ServerStream.SendMsg(m)
}

func (x *publicAPIPodStartServer) Recv() (*PodStartMessage, error) {
	m := new(PodStartMessage)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _PublicAPI_ContainerLogs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ContainerLogsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PublicAPIServer).ContainerLogs(m, &publicAPIContainerLogsServer{stream})
}

type PublicAPI_ContainerLogsServer interface {
	Send(*ContainerLogsResponse) error
	grpc.ServerStream
}

type publicAPIContainerLogsServer struct {
	grpc.ServerStream
}

func (x *publicAPIContainerLogsServer) Send(m *ContainerLogsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _PublicAPI_ContainerExec_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PublicAPIServer).ContainerExec(&publicAPIContainerExecServer{stream})
}

type PublicAPI_ContainerExecServer interface {
	Send(*ContainerExecResponse) error
	Recv() (*ContainerExecRequest, error)
	grpc.ServerStream
}

type publicAPIContainerExecServer struct {
	grpc.ServerStream
}

func (x *publicAPIContainerExecServer) Send(m *ContainerExecResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *publicAPIContainerExecServer) Recv() (*ContainerExecRequest, error) {
	m := new(ContainerExecRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _PublicAPI_Wait_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WaitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PublicAPIServer).Wait(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/types.PublicAPI/Wait",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PublicAPIServer).Wait(ctx, req.(*WaitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PublicAPI_Info_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PublicAPIServer).Info(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/types.PublicAPI/Info",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PublicAPIServer).Info(ctx, req.(*InfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PublicAPI_serviceDesc = grpc.ServiceDesc{
	ServiceName: "types.PublicAPI",
	HandlerType: (*PublicAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PodList",
			Handler:    _PublicAPI_PodList_Handler,
		},
		{
			MethodName: "PodCreate",
			Handler:    _PublicAPI_PodCreate_Handler,
		},
		{
			MethodName: "PodInfo",
			Handler:    _PublicAPI_PodInfo_Handler,
		},
		{
			MethodName: "PodRemove",
			Handler:    _PublicAPI_PodRemove_Handler,
		},
		{
			MethodName: "ContainerList",
			Handler:    _PublicAPI_ContainerList_Handler,
		},
		{
			MethodName: "ContainerInfo",
			Handler:    _PublicAPI_ContainerInfo_Handler,
		},
		{
			MethodName: "ImageList",
			Handler:    _PublicAPI_ImageList_Handler,
		},
		{
			MethodName: "VMList",
			Handler:    _PublicAPI_VMList_Handler,
		},
		{
			MethodName: "VMCreate",
			Handler:    _PublicAPI_VMCreate_Handler,
		},
		{
			MethodName: "VMRemove",
			Handler:    _PublicAPI_VMRemove_Handler,
		},
		{
			MethodName: "Wait",
			Handler:    _PublicAPI_Wait_Handler,
		},
		{
			MethodName: "Info",
			Handler:    _PublicAPI_Info_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "PodStart",
			Handler:       _PublicAPI_PodStart_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "ContainerLogs",
			Handler:       _PublicAPI_ContainerLogs_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ContainerExec",
			Handler:       _PublicAPI_ContainerExec_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
}

var fileDescriptor0 = []byte{
	// 2873 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xec, 0x3a, 0x5b, 0x6f, 0x1c, 0x59,
	0xd1, 0xe9, 0x19, 0xdb, 0x63, 0x9f, 0x19, 0xdf, 0xda, 0x76, 0x32, 0x9f, 0x13, 0x7d, 0x44, 0x2d,
	0xc2, 0x66, 0x83, 0xd6, 0xd9, 0x35, 0x11, 0x64, 0x0d, 0x91, 0x92, 0x8d, 0x83, 0xd6, 0x52, 0x92,
	0x1d, 0x8e, 0x43, 0x56, 0x88, 0x8b, 0xd4, 0x99, 0x6e, 0x4f, 0x5a, 0xe9, 0xe9, 0x1e, 0xba, 0x7b,
	0x9c, 0x0c, 0x3c, 0x2d, 0x8f, 0x2c, 0x6f, 0x48, 0x88, 0x8b, 0x78, 0xe1, 0x5f, 0xf0, 0x07, 0xf8,
	0x05, 0xfc, 0x06, 0x9e, 0x79, 0xe7, 0x85, 0xaa, 0x3a, 0xf7, 0x9e, 0xb6, 0x73, 0x59, 0x24, 0x5e,
	0x78, 0x49, 0x4e, 0x55, 0xd7, 0x39, 0xa7, 0x4e, 0xdd, 0xab, 0xc6, 0x6c, 0xb3, 0x9a, 0x4d, 0xe2,
	0xf2, 0x26, 0xfd, 0xbb, 0x37, 0x29, 0xf2, 0x2a, 0xf7, 0x17, 0x09, 0x08, 0xfe, 0xe0, 0xb1, 0xd5,
	0xfb, 0x79, 0x56, 0x85, 0x49, 0x16, 0x17, 0x83, 0xbc, 0xa8, 0x7c, 0x9f, 0x2d, 0x64, 0xe1, 0x38,
	0xee, 0x7b, 0x57, 0xbd, 0xeb, 0x2b, 0x9c, 0xd6, 0xfe, 0x2e, 0x5b, 0x7e, 0x9e, 0x97, 0x15, 0x7e,
	0xef, 0xb7, 0x00, 0xbf, 0xc8, 0x35, 0xec, 0x7f, 0x9d, 0xad, 0x0e, 0xed, 0x03, 0xfa, 0x6d, 0x22,
	0x70, 0x91, 0x78, 0x02, 0xdd, 0x3b, 0xcc, 0xd3, 0xfe, 0x02, 0x9d, 0xac, 0x61, 0xff, 0x22, 0x5b,
	0xc2, 0xd3, 0x8e, 0x06, 0xfd, 0x45, 0xfa, 0x22, 0xa1, 0xe0, 0x36, 0x5b, 0x7b, 0x90, 0x9d, 0x26,
	0x45, 0x9e, 0x8d, 0xe3, 0xac, 0x7a, 0x1a, 0x16, 0xfe, 0x06, 0x6b, 0xc7, 0xd9, 0xa9, 0x64, 0x0d,
	0x97, 0xfe, 0x36, 0x5b, 0x3c, 0x0d, 0xd3, 0x69, 0x4c, 0x6c, 0xad, 0x70, 0x01, 0x04, 0x3f, 0x66,
	0xdd, 0xa7, 0x79, 0x3a, 0x1d, 0xc7, 0x8f, 0xf2, 0x69, 0xd6, 0xfc, 0xa4, 0x2b, 0x6c, 0x65, 0x8c,
	0x1f, 0x07, 0x61, 0xf5, 0x5c, 0x6e, 0x36, 0x08, 0x64, 0xb7, 0x88, 0xc3, 0xe8, 0xb3, 0x2c, 0x9d,
	0xd1, 0x7b, 0x96, 0xb9, 0x86, 0x83, 0xf7, 0xd8, 0xea, 0xe7, 0x61, 0x52, 0x25, 0xd9, 0xe8, 0xb8,
	0x0a, 0xab, 0x69, 0x89, 0xfc, 0xc3, 0xc7, 0x32, 0xcf, 0xe4, 0x05, 0x12, 0x0a, 0x3e, 0x60, 0xab,
	0x7c, 0x9a, 0x65, 0x86, 0x10, 0xee, 0x2c, 0xab, 0xb0, 0xa8, 0xe2, 0xe8, 0x5e, 0x25, 0x69, 0x0d,
	0x22, 0xf8, 0xbd, 0xc7, 0xd8, 0x93, 0xb8, 0x18, 0x4b, 0x62, 0x60, 0x21, 0x7e, 0x95, 0x54, 0xf7,
	0xf3, 0x48, 0x30, 0x0e, 0x32, 0x57, 0xb0, 0x75, 0x63, 0xcb, 0xbe, 0xd1, 0xef, 0xb3, 0xce, 0x38,
	0x2e, 0xcb, 0x70, 0x14, 0x13, 0xd7, 0x2b, 0x5c, 0x81, 0xee, 0xd5, 0x0b, 0xb5, 0xab, 0xfd, 0xff,
	0x67, 0xec, 0x24, 0xc9, 0x92, 0xf2, 0x39, 0x7d, 0x16, 0x5a, 0xb0, 0x30, 0xc1, 0x3f, 0x3d, 0xb6,
	0xae, 0xad, 0x44, 0xf2, 0xd7, 0x24, 0xd4, 0xab, 0xac, 0xab, 0xd5, 0x7e, 0x74, 0x28, 0x99, 0xb3,
	0x51, 0xa8, 0xaf, 0xc9, 0xf3, 0xb0, 0x54, 0xfc, 0x09, 0xc0, 0xdf, 0x63, 0x9d, 0x97, 0x42, 0xa4,
	0xc4, 0x5b, 0x77, 0x7f, 0x7b, 0x4f, 0xd8, 0xaa, 0x23, 0x68, 0xae, 0x88, 0x90, 0xbe, 0x10, 0x92,
	0x25, 0x66, 0x0d, 0xbd, 0x23, 0x6f, 0xae, 0x88, 0xfc, 0x8f, 0x18, 0xab, 0x40, 0xb2, 0x49, 0x16,
	0xc2, 0x7b, 0xfb, 0x4b, 0xb4, 0x65, 0x53, 0x6e, 0x31, 0x22, 0xe7, 0x16, 0x51, 0xf0, 0xf7, 0xb6,
	0xe5, 0x18, 0x47, 0xd9, 0x49, 0xfe, 0xee, 0x0f, 0x4e, 0xc6, 0x46, 0x21, 0x02, 0x40, 0x45, 0xd1,
	0x02, 0xf6, 0x08, 0x65, 0x28, 0x10, 0xd5, 0x3e, 0xcc, 0xc7, 0xe3, 0x30, 0x8b, 0x4a, 0x78, 0x5b,
	0x1b, 0x1d, 0x45, 0xc1, 0xc8, 0x41, 0x58, 0x8c, 0x4a, 0x78, 0x00, 0xe2, 0x69, 0x8d, 0xaa, 0x7b,
	0x99, 0x17, 0x2f, 0xe0, 0x95, 0x87, 0x49, 0xd1, 0xef, 0x08, 0xd5, 0x19, 0x8c, 0x7f, 0x03, 0x04,
	0x0e, 0x0e, 0x58, 0xf6, 0x97, 0x61, 0x93, 0x11, 0x94, 0xe3, 0xf3, 0x5c, 0x90, 0xf8, 0xef, 0x09,
	0xf7, 0x5a, 0x21, 0xca, 0x1d, 0x49, 0xe9, 0xba, 0xa0, 0xf0, 0xba, 0x6f, 0xb3, 0xde, 0xa9, 0xf1,
	0xaf, 0xb2, 0xcf, 0x68, 0x87, 0x2f, 0x77, 0x58, 0xae, 0xc7, 0x1d, 0x3a, 0xf4, 0xdf, 0xaa, 0x9a,
	0xf5, 0xbb, 0xe4, 0x51, 0xb8, 0xf4, 0xaf, 0xb3, 0x75, 0x7a, 0xf9, 0x60, 0x9a, 0xa6, 0x83, 0x3c,
	0x4d, 0x86, 0xb3, 0x7e, 0x8f, 0xde, 0x50, 0x47, 0x93, 0xe5, 0xe4, 0x11, 0x08, 0x6c, 0x55, 0x5a,
	0x0e, 0x02, 0x60, 0x09, 0x4b, 0x25, 0x29, 0xaf, 0xbf, 0x46, 0x5a, 0xbd, 0x58, 0x7f, 0x9f, 0x54,
	0xad, 0xa4, 0x0a, 0x7e, 0xdd, 0x66, 0x2b, 0xfa, 0xdb, 0xff, 0x54, 0xfa, 0x5f, 0x55, 0x69, 0xf0,
	0x57, 0x08, 0x2b, 0xfc, 0x93, 0x43, 0x71, 0xf8, 0x71, 0x3e, 0x2d, 0x86, 0x94, 0x6a, 0xc6, 0x79,
	0x96, 0x54, 0x79, 0x51, 0x82, 0x5a, 0x48, 0x58, 0x0a, 0x36, 0x82, 0x6f, 0xd9, 0x82, 0x87, 0x60,
	0x78, 0x52, 0x3e, 0x01, 0x36, 0xa5, 0x3e, 0x24, 0x84, 0xa2, 0x9d, 0xe4, 0x3a, 0xdd, 0xd0, 0x1a,
	0x71, 0xd3, 0x32, 0x2e, 0x64, 0x88, 0xa3, 0x35, 0x2a, 0xee, 0x45, 0x3c, 0x2b, 0x30, 0x98, 0x2c,
	0x09, 0xc5, 0x49, 0xd0, 0xc9, 0x02, 0x9d, 0x5a, 0x16, 0x98, 0xb1, 0x95, 0x41, 0x1e, 0x09, 0xd6,
	0x1b, 0xed, 0x08, 0xd8, 0x2a, 0xe9, 0x49, 0x2a, 0x46, 0x0b, 0x08, 0xf1, 0x51, 0x91, 0x9c, 0x02,
	0x13, 0x92, 0x5d, 0x01, 0x81, 0xd8, 0xda, 0xc5, 0xb3, 0x48, 0xc6, 0x3f, 0x65, 0xc6, 0x35, 0xe9,
	0x70, 0x24, 0x09, 0x7e, 0xd5, 0x62, 0x1d, 0xb8, 0xfb, 0x78, 0x12, 0x0f, 0xc1, 0x16, 0x3a, 0x42,
	0x1d, 0x42, 0x5a, 0xdd, 0xfd, 0x0d, 0xb9, 0x53, 0x33, 0xc7, 0x15, 0x81, 0xff, 0x21, 0x63, 0xda,
	0x8c, 0x4b, 0xe0, 0xca, 0x26, 0xd7, 0xc6, 0xc3, 0x2d, 0x1a, 0x7f, 0x9f, 0x2d, 0xa5, 0xe1, 0xb3,
	0x38, 0x2d, 0x81, 0x57, 0xa4, 0xde, 0x35, 0x87, 0xe3, 0xed, 0x7b, 0x0f, 0xe9, 0xe3, 0x83, 0xac,
	0x2a, 0x66, 0x5c, 0x52, 0xa2, 0x2c, 0x4e, 0x87, 0x93, 0x29, 0x3d, 0x64, 0x91, 0xd3, 0x1a, 0xdf,
	0x3c, 0x8e, 0xc7, 0x79, 0x31, 0x23, 0xc1, 0x2f, 0x72, 0x09, 0xed, 0x7e, 0xcc, 0xba, 0xd6, 0x11,
	0x68, 0x4b, 0x20, 0x7a, 0x95, 0xde, 0x61, 0xd9, 0x9c, 0xde, 0x0f, 0x5a, 0xb7, 0xbd, 0xe0, 0x8b,
	0x16, 0x29, 0x40, 0x26, 0x23, 0x9d, 0x56, 0x3c, 0x3b, 0xad, 0x58, 0xe9, 0xb0, 0xe5, 0xa6, 0x43,
	0x93, 0x40, 0xdb, 0x4e, 0x02, 0x35, 0xa5, 0xc8, 0x82, 0x5d, 0x8a, 0xa8, 0xe0, 0x33, 0x90, 0xfe,
	0x2b, 0x00, 0x9d, 0x54, 0x9f, 0x24, 0xa0, 0xfb, 0x25, 0x2b, 0xa9, 0x22, 0xc2, 0xbf, 0xcb, 0xd6,
	0x87, 0x6e, 0x14, 0x02, 0x23, 0x6a, 0x9f, 0x13, 0xa3, 0xea, 0xe4, 0x26, 0x2d, 0xd3, 0x05, 0xcb,
	0x76, 0x5a, 0x46, 0x4c, 0xf0, 0x27, 0x8f, 0x0c, 0x41, 0x65, 0x27, 0x88, 0x0f, 0x91, 0x32, 0x41,
	0x5c, 0xe3, 0xfe, 0x70, 0x92, 0x3c, 0x05, 0x4d, 0x26, 0xba, 0x54, 0xb0, 0x30, 0xfe, 0x1a, 0x6b,
	0x9d, 0x8e, 0xa5, 0x04, 0x60, 0xe5, 0x07, 0x6c, 0xa1, 0x04, 0xb5, 0x4a, 0x1b, 0x5c, 0x73, 0x95,
	0xcd, 0xe9, 0x1b, 0x98, 0xa9, 0x0a, 0xb8, 0x22, 0xf3, 0x5a, 0xf6, 0x56, 0x0b, 0xb5, 0x7f, 0x01,
	0x0d, 0x1d, 0x51, 0x08, 0x44, 0xfe, 0xe0, 0xae, 0x44, 0x71, 0x07, 0x2b, 0x2a, 0x08, 0xc3, 0x02,
	0x22, 0x90, 0x8e, 0xb1, 0x1a, 0x16, 0x7e, 0x37, 0xc9, 0x9f, 0x84, 0x23, 0x61, 0x78, 0x2b, 0x5c,
	0xc3, 0x18, 0x9e, 0x71, 0x7d, 0x98, 0x8c, 0xe2, 0x12, 0xc2, 0xd4, 0x02, 0x7d, 0xb6, 0x51, 0xa8,
	0xf5, 0x21, 0xa8, 0x13, 0x33, 0x3d, 0xb2, 0xd8, 0xe6, 0x0a, 0xc4, 0xbd, 0x10, 0xf8, 0xaa, 0x69,
	0x98, 0x1e, 0x27, 0xbf, 0x10, 0x1a, 0x6b, 0x73, 0x1b, 0xe5, 0xdf, 0xd2, 0x06, 0x2f, 0x54, 0x75,
	0x45, 0xbe, 0x4e, 0xbf, 0xa3, 0xc9, 0xe4, 0xbf, 0x8a, 0x19, 0x7f, 0x83, 0xad, 0x49, 0x0d, 0xf2,
	0xf8, 0xe7, 0x53, 0xe0, 0xdf, 0xe4, 0x39, 0xcf, 0xca, 0x73, 0xc1, 0x77, 0xd9, 0xba, 0xa6, 0x2b,
	0x27, 0x79, 0x06, 0xd6, 0x7d, 0x9d, 0x75, 0x26, 0x02, 0x45, 0xa4, 0x8e, 0xc2, 0x88, 0x50, 0x7d,
	0x0e, 0x0e, 0xe8, 0x92, 0x87, 0x49, 0x59, 0x9d, 0x7b, 0x09, 0xb9, 0xee, 0x58, 0xeb, 0x83, 0xd6,
	0xc1, 0x0b, 0xb6, 0xaa, 0xf7, 0x96, 0xd3, 0xf4, 0xac, 0xad, 0x7d, 0x62, 0xe6, 0x31, 0x06, 0x41,
	0xe9, 0x6a, 0x12, 0xd4, 0x87, 0xb6, 0xcd, 0xa1, 0x14, 0x1b, 0x85, 0x11, 0x49, 0x37, 0x93, 0x26,
	0x73, 0x8f, 0x5e, 0x29, 0x2f, 0x13, 0xaf, 0xdc, 0xa3, 0x83, 0x11, 0x25, 0x03, 0xdc, 0xb6, 0x79,
	0xa5, 0xe1, 0x8a, 0x2b, 0xa2, 0xe0, 0x67, 0x6c, 0x5b, 0xfb, 0xd5, 0x3b, 0xbd, 0x18, 0xbd, 0x3a,
	0x9c, 0xbe, 0x4a, 0xd2, 0x24, 0x2c, 0x54, 0xf1, 0x6f, 0x10, 0xc1, 0x97, 0x1e, 0xdb, 0xaa, 0x5d,
	0x40, 0x62, 0xa9, 0x95, 0x0d, 0xde, 0x7c, 0xd9, 0x60, 0x37, 0x4a, 0x96, 0xa0, 0x5c, 0xa4, 0xe1,
	0xb3, 0x6d, 0xf3, 0x79, 0x96, 0xc0, 0x7e, 0xc4, 0x76, 0xea, 0xcc, 0x08, 0xb1, 0xdd, 0xb5, 0x2e,
	0xb3, 0x84, 0xb7, 0x5b, 0x0f, 0x3d, 0x96, 0x08, 0xdd, 0x0d, 0xc1, 0x2d, 0x4b, 0x90, 0xb6, 0x7d,
	0x82, 0x78, 0x34, 0xa1, 0x6a, 0x62, 0x34, 0x22, 0x38, 0xb6, 0x18, 0x72, 0xac, 0xf5, 0xc0, 0x62,
	0xc8, 0xb2, 0xd9, 0xb9, 0xe2, 0x85, 0x36, 0xb9, 0xa4, 0xc1, 0x80, 0xf5, 0x9e, 0x3e, 0xb2, 0x64,
	0xad, 0xb4, 0xe6, 0x59, 0x5a, 0xd3, 0x72, 0x6b, 0x35, 0xcb, 0xad, 0xed, 0xc8, 0xed, 0x63, 0xb6,
	0xaa, 0x4e, 0x7c, 0x5b, 0x87, 0xb8, 0xc3, 0xd6, 0x34, 0x33, 0xe2, 0x69, 0xdf, 0x64, 0x4b, 0xa7,
	0x63, 0x4b, 0xc8, 0x5b, 0xaa, 0x68, 0xb2, 0x78, 0xe6, 0x92, 0x24, 0xf8, 0x09, 0xdb, 0xa0, 0x60,
	0x62, 0x5f, 0x4e, 0x71, 0x3e, 0x85, 0xe6, 0xe3, 0x1e, 0x96, 0x82, 0x9e, 0x8a, 0xf3, 0x0a, 0x43,
	0x15, 0x0e, 0x41, 0xaa, 0x94, 0x10, 0x10, 0x06, 0x9a, 0x30, 0x4d, 0xa5, 0x8d, 0xe2, 0x32, 0xb8,
	0xcf, 0x36, 0xad, 0xd3, 0xb5, 0x0b, 0xad, 0x24, 0x0a, 0x59, 0xab, 0x12, 0x74, 0x5c, 0xe3, 0x86,
	0x04, 0x63, 0xcd, 0xd3, 0x47, 0xf7, 0x29, 0x66, 0x2a, 0x0e, 0xe1, 0x26, 0xcc, 0xe9, 0xa2, 0x0f,
	0x6d, 0xbb, 0x29, 0xbd, 0x65, 0xa7, 0x74, 0x08, 0x68, 0x1b, 0x66, 0xb3, 0x64, 0xa0, 0x41, 0x5f,
	0xc1, 0x35, 0xbc, 0x84, 0xc3, 0x9e, 0x53, 0x7d, 0x49, 0x13, 0xd9, 0xf7, 0xf0, 0x38, 0x45, 0x66,
	0x8e, 0x1b, 0x9a, 0xae, 0x98, 0xd6, 0xa8, 0xbf, 0x61, 0x08, 0xe5, 0x9c, 0x52, 0x3f, 0x01, 0xc1,
	0x6f, 0x3d, 0xb6, 0xf9, 0x43, 0xa8, 0xf1, 0xee, 0xd7, 0x67, 0x11, 0x7a, 0x9a, 0xe1, 0xbd, 0x6e,
	0x9a, 0xd1, 0x6a, 0x9a, 0x66, 0x80, 0xb3, 0xc3, 0xa9, 0xa7, 0xc9, 0x30, 0xb6, 0x26, 0x1e, 0x36,
	0xea, 0xbc, 0x79, 0x47, 0xf0, 0x53, 0xb6, 0x85, 0x4c, 0xc9, 0xf2, 0x2c, 0x3e, 0x89, 0x21, 0xed,
	0x0d, 0x45, 0xbd, 0x8a, 0xc3, 0x08, 0xf9, 0x7c, 0x5c, 0xa3, 0x94, 0x45, 0xf5, 0xa6, 0x34, 0x2f,
	0xa0, 0x73, 0xe7, 0x13, 0x5f, 0xc8, 0x47, 0x7f, 0x3f, 0x49, 0x5f, 0x73, 0x3a, 0x9c, 0x02, 0x96,
	0x14, 0x67, 0x26, 0x18, 0x69, 0x98, 0xe8, 0xa1, 0x1b, 0x56, 0x61, 0x1b, 0xd7, 0xba, 0x7a, 0x5e,
	0xb0, 0xaa, 0x67, 0x10, 0xfc, 0xa8, 0xc8, 0xa7, 0x13, 0x59, 0x52, 0x0b, 0x20, 0xf8, 0x17, 0x74,
	0xcf, 0x8e, 0xe0, 0x1b, 0x4b, 0xe4, 0xe6, 0x7a, 0x1e, 0x52, 0x09, 0x36, 0x3b, 0x51, 0xa2, 0x2a,
	0x64, 0x05, 0xa2, 0x72, 0x8a, 0x98, 0x0a, 0x2c, 0xd9, 0x57, 0x08, 0x46, 0x5c, 0xa4, 0xea, 0x48,
	0x16, 0x4d, 0x47, 0x72, 0x1b, 0xa2, 0xc0, 0xac, 0x1c, 0x56, 0x29, 0xb5, 0x59, 0xdd, 0xfd, 0xab,
	0xd2, 0xfa, 0x1d, 0x0e, 0xf7, 0x8e, 0x89, 0x44, 0x66, 0x76, 0x41, 0xef, 0xbf, 0xcf, 0x16, 0xa0,
	0x39, 0x52, 0xd5, 0xc0, 0x19, 0xfd, 0x13, 0x91, 0x50, 0xd9, 0x21, 0xba, 0x3a, 0xea, 0xcb, 0x80,
	0x6d, 0x09, 0xa2, 0x7b, 0xc7, 0x78, 0xea, 0x24, 0x4f, 0xb2, 0x8a, 0x5a, 0x31, 0x70, 0x6f, 0x83,
	0x01, 0xff, 0x94, 0xfd, 0x9c, 0xe8, 0xb9, 0xfa, 0x4d, 0xdc, 0xd9, 0x3d, 0xdd, 0x2d, 0x53, 0xf3,
	0x77, 0x9d, 0xa8, 0xde, 0x60, 0x55, 0xa6, 0xfa, 0x87, 0x5b, 0x50, 0xb9, 0x25, 0x34, 0x63, 0xf5,
	0x5b, 0x1c, 0x4b, 0xe1, 0x82, 0x0c, 0x8b, 0x1a, 0x4b, 0x22, 0x6f, 0x55, 0xd4, 0x1c, 0xb0, 0x1e,
	0x1e, 0x0b, 0x0e, 0x2b, 0x5a, 0x1e, 0xd5, 0x12, 0x78, 0x8d, 0x2d, 0x81, 0x1b, 0x3f, 0x4e, 0xd8,
	0xb2, 0x62, 0xe9, 0xac, 0x51, 0x24, 0x70, 0x99, 0x47, 0xd8, 0xae, 0x49, 0x9b, 0x55, 0x30, 0xf2,
	0x38, 0x2d, 0x12, 0x69, 0x35, 0xb8, 0x14, 0x4a, 0xc9, 0x2a, 0x10, 0xb6, 0x6a, 0xca, 0x25, 0x88,
	0x71, 0xd8, 0x88, 0xeb, 0xb3, 0x49, 0x85, 0xf5, 0xb0, 0xb2, 0x6f, 0xaf, 0xb9, 0x3b, 0x6c, 0xcd,
	0x75, 0x87, 0xba, 0x53, 0x6d, 0xbb, 0x9d, 0x2a, 0xfa, 0x20, 0x33, 0xc7, 0xff, 0x47, 0xfa, 0xc3,
	0x9b, 0x6c, 0x29, 0x27, 0x36, 0x65, 0x79, 0x7e, 0x69, 0x4e, 0xe9, 0xe2, 0x15, 0x5c, 0x92, 0x05,
	0xbf, 0x14, 0x2e, 0x78, 0x04, 0xef, 0x2d, 0x4e, 0x42, 0x71, 0xf2, 0xb3, 0x22, 0x89, 0x46, 0x8a,
	0x0f, 0x09, 0x51, 0x69, 0x3e, 0x91, 0x5c, 0xc0, 0x0a, 0xe9, 0x92, 0x13, 0xe2, 0x57, 0x72, 0x20,
	0x20, 0x14, 0xef, 0x38, 0x1c, 0x4a, 0x41, 0xe2, 0x12, 0x85, 0x33, 0x82, 0x40, 0xff, 0x32, 0x9c,
	0x49, 0xf7, 0x57, 0x60, 0xf0, 0x29, 0xf3, 0xf1, 0xf2, 0x63, 0x11, 0x12, 0x3f, 0x09, 0x87, 0x2f,
	0x62, 0xf0, 0x04, 0xd9, 0x5e, 0xc1, 0x6d, 0x9e, 0x69, 0xaf, 0xe0, 0x46, 0x19, 0x91, 0x27, 0xb5,
	0xf9, 0x32, 0xc2, 0xc1, 0x1f, 0x3d, 0xd6, 0xb5, 0x8e, 0xa2, 0xa6, 0x4b, 0x2c, 0xf5, 0x31, 0x06,
	0xe1, 0xc4, 0xdd, 0x56, 0x6d, 0xce, 0x6c, 0xa2, 0xf6, 0x64, 0x3e, 0x6a, 0x23, 0x0a, 0x64, 0xbc,
	0x88, 0xf7, 0x8a, 0xb6, 0xa2, 0xbb, 0xff, 0x7f, 0x96, 0x88, 0xdd, 0x97, 0x70, 0x41, 0x17, 0xfc,
	0xce, 0x63, 0x3d, 0x2c, 0x44, 0xf3, 0x11, 0x78, 0xea, 0x49, 0x32, 0x42, 0x4d, 0xe3, 0x1e, 0xa5,
	0x69, 0x5c, 0xfb, 0xdf, 0x61, 0x4b, 0x43, 0xfa, 0x2a, 0x7b, 0xee, 0xaf, 0x59, 0x15, 0xac, 0xda,
	0xb8, 0x27, 0xfe, 0x93, 0xd1, 0x47, 0x90, 0xa3, 0x0b, 0x5a, 0xe8, 0xb7, 0x72, 0xc1, 0x8c, 0x6d,
	0x63, 0xc8, 0x18, 0x87, 0x93, 0x09, 0xd8, 0xea, 0xe7, 0xcf, 0x93, 0x8a, 0x72, 0xbb, 0x7f, 0x83,
	0x6d, 0x24, 0x68, 0x10, 0x59, 0x98, 0x3e, 0x8e, 0x2b, 0x0c, 0xac, 0x6a, 0xcc, 0x32, 0x87, 0x47,
	0xda, 0xf8, 0x55, 0x8d, 0xb6, 0x25, 0x68, 0xeb, 0xf8, 0xe0, 0xcf, 0x8b, 0xac, 0x83, 0x62, 0x82,
	0x37, 0x35, 0xb5, 0x7a, 0x28, 0x2d, 0x3b, 0xcd, 0x28, 0x58, 0xcb, 0xab, 0x6d, 0xc9, 0xeb, 0x5d,
	0xc3, 0xbc, 0x99, 0x56, 0x2c, 0xcd, 0x85, 0x45, 0xe0, 0xab, 0x71, 0x5a, 0x71, 0x13, 0x13, 0xa9,
	0xf4, 0xc3, 0x0e, 0xf9, 0xd5, 0x96, 0xb5, 0x4b, 0x45, 0x30, 0xae, 0x89, 0xfc, 0x6b, 0xac, 0x9d,
	0xe6, 0x23, 0x6a, 0xc6, 0x0d, 0xad, 0xad, 0x49, 0x8e, 0xdf, 0x91, 0xbb, 0x28, 0x2b, 0x65, 0xb0,
	0xc7, 0x25, 0x44, 0x6d, 0x7b, 0xfa, 0xc2, 0x9c, 0x5e, 0xc6, 0x09, 0xf5, 0xce, 0x04, 0xe6, 0x9a,
	0x8a, 0xda, 0x22, 0xd2, 0xaf, 0xd7, 0xa3, 0xb6, 0xf8, 0x0a, 0x25, 0xa8, 0x4e, 0x09, 0x22, 0xbc,
	0x6f, 0xce, 0xa7, 0x04, 0x9d, 0x09, 0x80, 0x93, 0x44, 0x05, 0x85, 0xb2, 0xbf, 0x3a, 0xc7, 0x89,
	0x8e, 0x18, 0xdc, 0xa2, 0x83, 0xfc, 0xb1, 0x2c, 0x5d, 0x05, 0x67, 0xad, 0xf6, 0x70, 0xd0, 0x72,
	0x0f, 0xae, 0x69, 0xfc, 0x1f, 0xb0, 0x9d, 0x49, 0x83, 0x05, 0x96, 0xfd, 0x75, 0x12, 0xdd, 0x65,
	0x2d, 0xba, 0x79, 0x1a, 0xde, 0xbc, 0xf3, 0xab, 0xf4, 0xd9, 0x9c, 0x6d, 0x80, 0x92, 0xdc, 0xa2,
	0x56, 0x34, 0xd0, 0x38, 0xdb, 0xa8, 0x35, 0xd0, 0xd2, 0x60, 0xb8, 0xfa, 0xdc, 0xdc, 0x5c, 0x04,
	0xef, 0xb3, 0x4d, 0xeb, 0x4c, 0x59, 0x9c, 0x36, 0xb7, 0xef, 0xd7, 0xe9, 0x7a, 0xb7, 0xdc, 0x6d,
	0xa6, 0xbc, 0x43, 0x87, 0xbe, 0x73, 0xc5, 0xfb, 0x37, 0xcf, 0xee, 0x7f, 0xf3, 0x51, 0xf9, 0x46,
	0x6d, 0x1b, 0x75, 0x18, 0x79, 0x9a, 0xe6, 0x2f, 0xe9, 0xb4, 0x65, 0x2e, 0x21, 0x2c, 0x5d, 0xaa,
	0x64, 0x8c, 0x7e, 0x37, 0x9e, 0x94, 0xb2, 0xd2, 0xb4, 0x30, 0xe4, 0xbe, 0x61, 0xa2, 0x67, 0xac,
	0xb8, 0x46, 0xc6, 0xca, 0x04, 0x0a, 0x09, 0x55, 0x11, 0x12, 0x20, 0x3a, 0xb1, 0x28, 0x9f, 0x56,
	0x34, 0x76, 0x59, 0xe6, 0x12, 0x92, 0xf8, 0xb8, 0x28, 0xe4, 0x84, 0x55, 0x42, 0x20, 0xdc, 0x9d,
	0xda, 0x3b, 0xa4, 0x2c, 0x36, 0x84, 0x03, 0xe2, 0x13, 0x7a, 0xe4, 0x6b, 0x58, 0x6e, 0x1c, 0x52,
	0x8e, 0x3c, 0xe7, 0x97, 0x29, 0xd3, 0x08, 0xb6, 0x9c, 0x46, 0x70, 0x95, 0x75, 0xad, 0xe6, 0x36,
	0xf8, 0xb2, 0xcd, 0x7a, 0x4e, 0xdb, 0x0a, 0xb1, 0x4c, 0x6b, 0xa8, 0x95, 0x1c, 0xa2, 0x40, 0x9c,
	0x19, 0x2a, 0xea, 0xc3, 0xf6, 0x57, 0xcc, 0x9d, 0x58, 0xc5, 0x96, 0x32, 0xbd, 0x48, 0xc8, 0xca,
	0xea, 0x0b, 0x4e, 0x56, 0xff, 0x80, 0x75, 0x22, 0x3d, 0x4f, 0xb3, 0x9b, 0x47, 0xfb, 0x45, 0x5c,
	0xd1, 0x60, 0x68, 0x8c, 0x72, 0xc8, 0x40, 0x05, 0xcf, 0xf3, 0x0a, 0x7f, 0x1d, 0x10, 0x53, 0x47,
	0x17, 0x09, 0xae, 0xea, 0x27, 0x59, 0x14, 0xbf, 0x42, 0xa7, 0x84, 0x16, 0x32, 0x8a, 0x20, 0x7a,
	0x95, 0xf2, 0x87, 0x84, 0x86, 0x2f, 0x38, 0xb1, 0x8f, 0x5f, 0xc5, 0xc3, 0x29, 0x96, 0x0d, 0xe2,
	0x5e, 0x39, 0x6c, 0xac, 0xa3, 0xa9, 0xe6, 0x89, 0xc7, 0x4f, 0xf2, 0x2a, 0x4c, 0x21, 0xb6, 0xe1,
	0xf8, 0x4c, 0xc3, 0x62, 0xde, 0x1e, 0x61, 0x68, 0x43, 0x3c, 0xad, 0xf1, 0xe4, 0x1c, 0x5a, 0x87,
	0x90, 0x7e, 0xc4, 0x9b, 0x95, 0x55, 0x3c, 0xa6, 0x5f, 0x0a, 0xe0, 0xe4, 0x1a, 0x5a, 0x2b, 0xad,
	0x67, 0x94, 0x16, 0xfc, 0xc6, 0x36, 0xe6, 0x07, 0xc0, 0x8a, 0x32, 0xe6, 0xd7, 0x0f, 0x5b, 0xac,
	0x6a, 0xbc, 0xe5, 0x56, 0xe3, 0x98, 0x37, 0xc2, 0x91, 0x2a, 0x12, 0x61, 0xa9, 0x32, 0xc9, 0x82,
	0xc9, 0x24, 0x68, 0xc2, 0x15, 0x94, 0x94, 0x64, 0xc2, 0x3d, 0x2e, 0x80, 0xe0, 0xa6, 0x65, 0x92,
	0x82, 0x1b, 0x69, 0x24, 0xc6, 0xb6, 0x85, 0x55, 0x4a, 0x28, 0x08, 0x69, 0x9c, 0x75, 0x8c, 0x49,
	0xeb, 0x91, 0x1c, 0x3c, 0xbf, 0xf9, 0x18, 0x6a, 0x9e, 0x4f, 0xa0, 0x8a, 0xc2, 0x2a, 0x24, 0x46,
	0x7b, 0x9c, 0xd6, 0x70, 0x45, 0x17, 0x7f, 0x23, 0x7d, 0x33, 0x2f, 0x87, 0xaf, 0x50, 0x0c, 0x41,
	0x70, 0x2e, 0x8f, 0x22, 0xf5, 0x9b, 0xb7, 0x46, 0xe0, 0x2b, 0xb2, 0xfc, 0xd3, 0x30, 0x1b, 0x49,
	0x3f, 0x97, 0x50, 0x70, 0x83, 0xf5, 0xc4, 0x15, 0xf2, 0xb5, 0xe7, 0xfc, 0x30, 0xbd, 0xff, 0x8f,
	0x0e, 0x5b, 0x19, 0x4c, 0x9f, 0x41, 0x82, 0xbe, 0x37, 0x38, 0xf2, 0x0f, 0x68, 0x3c, 0x4d, 0x75,
	0xc7, 0x4e, 0x7d, 0x6a, 0x47, 0xfc, 0xee, 0x5e, 0x9c, 0x1b, 0xe6, 0xd1, 0x1d, 0xc1, 0x05, 0xff,
	0x2e, 0x8d, 0xf7, 0x45, 0x70, 0xf5, 0x2f, 0x19, 0x32, 0x27, 0x84, 0xef, 0xf6, 0xe7, 0x3f, 0xe8,
	0x13, 0x0e, 0xcc, 0x70, 0x7c, 0xa7, 0x36, 0x19, 0x9d, 0xbf, 0xdd, 0x76, 0x7a, 0x7d, 0xbb, 0x88,
	0xc2, 0xf6, 0xed, 0x4e, 0x04, 0xb7, 0x6f, 0x77, 0x03, 0x36, 0x9c, 0xf0, 0xd0, 0xfa, 0xf9, 0x98,
	0x24, 0x70, 0xb9, 0x79, 0xf4, 0x26, 0x4e, 0xba, 0x72, 0xc6, 0x5c, 0xae, 0xe9, 0x34, 0x7a, 0xd1,
	0xe5, 0xc6, 0xb9, 0xd9, 0x59, 0xa7, 0xcd, 0xbf, 0x4e, 0x4f, 0x89, 0xf4, 0xeb, 0xea, 0x53, 0x29,
	0xfd, 0xba, 0xb9, 0x81, 0x12, 0x9c, 0x00, 0x25, 0xad, 0x98, 0x6e, 0xf9, 0xdb, 0xb5, 0x61, 0x97,
	0xd8, 0xbb, 0x53, 0x1f, 0x81, 0xa9, 0x8d, 0x77, 0xd8, 0xb2, 0x1a, 0x0f, 0xf9, 0x17, 0x35, 0x91,
	0xab, 0xd4, 0x4b, 0x73, 0x78, 0x77, 0xbb, 0x54, 0x8b, 0xd9, 0xee, 0x6a, 0xe5, 0xd2, 0x1c, 0xde,
	0x7a, 0xf8, 0xb2, 0x72, 0x48, 0xff, 0xa2, 0xf3, 0xc3, 0x85, 0xf6, 0xd0, 0xdd, 0x33, 0xf0, 0xc1,
	0x85, 0xeb, 0xde, 0x87, 0x9e, 0xff, 0xd8, 0x56, 0x2b, 0xa4, 0xa5, 0x06, 0xb5, 0x9a, 0xa4, 0xdb,
	0xa0, 0x56, 0x2b, 0x93, 0x05, 0x17, 0xe0, 0xbc, 0x81, 0x75, 0x1e, 0xc6, 0x94, 0xf9, 0xf3, 0xac,
	0xb8, 0x37, 0x7f, 0x9e, 0x1d, 0x86, 0x24, 0x87, 0x1f, 0xb1, 0x05, 0x74, 0x57, 0xdf, 0xb7, 0xfe,
	0x84, 0x42, 0xed, 0xdf, 0x72, 0x70, 0x5a, 0x2c, 0xb0, 0x45, 0xfc, 0x86, 0xa4, 0x34, 0x6e, 0xd9,
	0xd2, 0x96, 0x83, 0x53, 0x5b, 0x9e, 0x2d, 0x51, 0x57, 0xf5, 0xad, 0x7f, 0x07, 0x00, 0x00, 0xff,
	0xff, 0x8e, 0x2a, 0x01, 0x2f, 0x5a, 0x24, 0x00, 0x00,
}
